/**
 * Badge Component Generator
 *
 * Generates a single Badge ComponentSet in Figma with variant property.
 * Reads variant definitions from component-registry.json (the source of truth).
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  getOrCreateSection,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const badgeProps = registry.components.Badge.props;
const variantProp = badgeProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Badge base styles from badgeVariants() in badge.tsx
 */
const BADGE_BASE_STYLES = "rounded-full px-2 py-0.5 text-xs";

/**
 * Helper to set white text color (not a variable)
 */
function setWhiteTextColor(textNode: TextNode): void {
  const fill: SolidPaint = {
    type: "SOLID",
    color: { r: 1, g: 1, b: 1 },
  };
  textNode.fills = [fill];
}

/**
 * Helper to bind text color to a variable
 */
function bindTextColorToVariable(textNode: TextNode, variableId: string): void {
  const variable = figma.variables.getVariableById(variableId);
  if (!variable) {
    console.warn("Variable not found: " + variableId);
    return;
  }

  var fill: SolidPaint = {
    type: "SOLID",
    color: { r: 1, g: 1, b: 1 },
  };

  fill = figma.variables.setBoundVariableForPaint(fill, "color", variable);
  textNode.fills = [fill];
}

/**
 * Create a single Badge component with the specified variant
 */
async function createBadgeComponent(variant: string): Promise<ComponentNode> {
  const classes = variantProp.classes[variant] || "";
  const description = variantProp.descriptions[variant] || "";

  // Parse base styles and variant-specific styles
  const baseStyles = parseTailwindClasses(BADGE_BASE_STYLES);
  const variantStyles = parseTailwindClasses(classes);

  // Create component
  const component = figma.createComponent();
  component.name = "variant=" + variant;
  component.description = description;

  // Set up auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.paddingLeft = baseStyles.paddingX || 8;
  component.paddingRight = baseStyles.paddingX || 8;
  component.paddingTop = baseStyles.paddingY || 2;
  component.paddingBottom = baseStyles.paddingY || 2;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.cornerRadius = baseStyles.borderRadius || 9999;

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background
    component.fills = [];
  }

  // Apply border if variant has one
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);

      if (variantStyles.borderStyle === "dashed") {
        component.dashPattern = [4, 4];
      }
    }
  }

  // Create text label
  const textNode = await createTextNode(
    "Badge",
    baseStyles.fontSize || 12,
    500, // font-medium
  );
  textNode.name = "Label";

  // Apply text color from variant
  if (variantStyles.isWhiteText) {
    setWhiteTextColor(textNode);
  } else if (variantStyles.textVariable) {
    const textVar = getVariableByName(variantStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 80;

/**
 * Generate Badge ComponentSet with variant property
 *
 * Creates a single "Badge" ComponentSet with variants derived from
 * component-registry.json.
 *
 * @param startY - Y position to start placing the section
 * @returns The Y position after this section (for next section placement)
 */
export async function generateBadgeComponents(startY: number): Promise<number> {
  if (startY === undefined) startY = 100;

  // Find or create Components page
  var componentsPage = figma.root.children.find(function (page) {
    return page.type === "PAGE" && page.name === "Components";
  }) as PageNode | undefined;

  if (!componentsPage) {
    componentsPage = figma.createPage();
    componentsPage.name = "Components";
  }

  figma.currentPage = componentsPage;

  // Create Badge section
  const section = getOrCreateSection(componentsPage, "Badge");

  // Get variant keys from the registry
  const variants = variantProp.values;
  const components: ComponentNode[] = [];

  // Track position for laying out components before combining
  var currentX = 0;
  var componentGap = 20;

  for (var i = 0; i < variants.length; i++) {
    const component = await createBadgeComponent(variants[i]);
    // Position each component horizontally before combining
    component.x = currentX;
    component.y = 0;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }

  // Combine all variants into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, componentsPage);
  componentSet.name = "Badge";
  componentSet.description = "Badge component with variant styles";

  // Move ComponentSet into section
  section.appendChild(componentSet);

  // Position ComponentSet with padding
  componentSet.x = SECTION_PADDING;
  componentSet.y = SECTION_PADDING;

  // Resize section to fit content with padding
  const totalWidth = componentSet.width + SECTION_PADDING * 2;
  const totalHeight = componentSet.height + SECTION_PADDING * 2;
  section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position section on page
  section.x = 100;
  section.y = startY;

  console.log(
    "✅ Generated Badge ComponentSet with " + variants.length + " variants",
  );
  console.log(
    "Badge section height: " +
      totalHeight +
      ", nextY: " +
      (startY + totalHeight + SECTION_GAP),
  );

  // Use totalHeight (calculated) instead of section.height (may not be updated yet)
  return startY + totalHeight + SECTION_GAP;
}
