/**
 * Banner Component Generator
 *
 * Generates a single Banner ComponentSet in Figma with variant property.
 * Reads variant definitions from component-registry.json (the source of truth).
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";
import { createIconInstance, bindIconColor } from "./icon-utils";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const bannerProps = registry.components.Banner.props;
const variantProp = bannerProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Banner base styles from bannerVariants() in banner.tsx
 */
const BANNER_BASE_STYLES =
  "flex w-full items-center gap-2 rounded-lg border px-4 py-1.5 text-base";

/**
 * Create a single Banner component with the specified variant
 */
async function createBannerComponent(variant: string): Promise<ComponentNode> {
  const classes = variantProp.classes[variant] || "";
  const description = variantProp.descriptions[variant] || "";

  // Parse base styles and variant-specific styles
  const baseStyles = parseTailwindClasses(BANNER_BASE_STYLES);
  const variantStyles = parseTailwindClasses(classes);

  // Create component
  const component = figma.createComponent();
  component.name = "variant=" + variant;
  component.description = description;

  // Set up auto-layout (horizontal for banner with icon + text)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.itemSpacing = baseStyles.gap || 8; // gap-2 = 8px
  component.paddingLeft = baseStyles.paddingX || 16; // px-4 = 16px
  component.paddingRight = baseStyles.paddingX || 16;
  component.paddingTop = baseStyles.paddingY || 6; // py-1.5 = 6px
  component.paddingBottom = baseStyles.paddingY || 6;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.cornerRadius = baseStyles.borderRadius || 8; // rounded-lg = 8px

  // Apply fill from variant (bg-info/20, bg-alert/20, bg-error/20)
  // Opacity variants are stored as separate Figma variables (e.g., "color-info/20")
  // generated by sync-tokens-to-figma.ts, so no runtime opacity needed
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background
    component.fills = [];
  }

  // Apply border (all banner variants have borders)
  if (variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Create icon based on variant
  // - default (info): ph-info
  // - alert: ph-warning
  // - error: ph-warning-circle
  const BANNER_ICONS: Record<string, string> = {
    default: "ph-info",
    alert: "ph-warning",
    error: "ph-warning-circle",
  };

  const iconId = BANNER_ICONS[variant] || "ph-info";
  const iconSize = 16;
  const iconInstance = createIconInstance(iconId, iconSize);

  if (iconInstance) {
    iconInstance.name = "Icon";

    // Bind icon color to variant text color
    if (variantStyles.textVariable) {
      bindIconColor(iconInstance, variantStyles.textVariable);
    }

    component.appendChild(iconInstance);
  } else {
    // Fallback: create a placeholder rectangle if icon not found
    const iconPlaceholder = figma.createRectangle();
    iconPlaceholder.name = "Icon (placeholder)";
    iconPlaceholder.resize(iconSize, iconSize);
    iconPlaceholder.cornerRadius = 2;

    if (variantStyles.textVariable) {
      const iconColorVar = getVariableByName(variantStyles.textVariable);
      if (iconColorVar) {
        bindFillToVariable(iconPlaceholder, iconColorVar.id);
      }
    }

    component.appendChild(iconPlaceholder);
  }

  // Create text label
  const textNode = await createTextNode(
    "This is a banner message",
    baseStyles.fontSize || 16, // text-base = 16px
    400, // normal weight
  );
  textNode.name = "Text";

  // Apply text color from variant
  if (variantStyles.textVariable) {
    const textVar = getVariableByName(variantStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Generate Banner ComponentSet with variant property
 *
 * Creates a single "Banner" ComponentSet with variants derived from
 * component-registry.json. Creates both light and dark mode sections.
 *
 * @param startY - Y position to start placing the section
 * @returns The Y position after this section (for next section placement)
 */
export async function generateBannerComponents(
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  // Find or create Components page
  let componentsPage = figma.root.children.find(function (page) {
    return page.type === "PAGE" && page.name === "Components";
  }) as PageNode | undefined;

  if (!componentsPage) {
    componentsPage = figma.createPage();
    componentsPage.name = "Components";
  }

  figma.currentPage = componentsPage;

  // Get variant keys from the registry
  const variants = variantProp.values;
  const components: ComponentNode[] = [];

  // Track row labels: { y, text }
  const rowLabels: { y: number; text: string }[] = [];

  // Layout spacing - vertical layout with labels
  const rowGap = 48;
  const labelColumnWidth = 160; // Space for labels on the left

  // Track position for laying out components vertically
  let currentY = 0;

  for (let i = 0; i < variants.length; i++) {
    const variant = variants[i];
    const component = await createBannerComponent(variant);

    // Record row label
    rowLabels.push({ y: currentY, text: "variant=" + variant });

    // Position each component vertically with label offset
    component.x = labelColumnWidth;
    component.y = currentY;
    currentY += component.height + rowGap;
    components.push(component);
  }

  // Combine all variants into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, componentsPage);
  componentSet.name = "Banner";
  componentSet.description = "Banner component with variant styles";

  // Calculate content dimensions (add label column width)
  const contentWidth = componentSet.width + labelColumnWidth;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(componentsPage, "Banner", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(componentsPage, "Banner", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8, // +8 to vertically center with banner
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated Banner ComponentSet with " +
      variants.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}
