/**
 * Button Component Generator
 *
 * Generates a single Button ComponentSet in Figma with properties:
 * - variant: primary, secondary, ghost, destructive, secondary-destructive, outline
 * - size: xs, sm, base, lg
 *
 * Reads variant definitions from component-registry.json (the source of truth).
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  getOrCreateSection,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const buttonProps = registry.components.Button.props;
const variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};
const sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 80;

/**
 * Helper to set white text color (not a variable)
 */
function setWhiteTextColor(textNode: TextNode): void {
  const fill: SolidPaint = {
    type: "SOLID",
    color: { r: 1, g: 1, b: 1 },
  };
  textNode.fills = [fill];
}

/**
 * Helper to bind text color to a variable
 */
function bindTextColorToVariable(textNode: TextNode, variableId: string): void {
  const variable = figma.variables.getVariableById(variableId);
  if (!variable) {
    console.warn("Variable not found: " + variableId);
    return;
  }

  var fill: SolidPaint = {
    type: "SOLID",
    color: { r: 1, g: 1, b: 1 },
  };

  fill = figma.variables.setBoundVariableForPaint(fill, "color", variable);
  textNode.fills = [fill];
}

/**
 * Create a single button component for a variant/size combination
 */
async function createButtonComponent(
  variant: string,
  size: string,
): Promise<ComponentNode> {
  const variantClasses = variantProp.classes[variant] || "";
  const sizeClasses = sizeProp.classes[size] || "";
  const variantDesc = variantProp.descriptions[variant] || "";
  const sizeDesc = sizeProp.descriptions[size] || "";

  // Parse variant styles and size styles
  const variantStyles = parseTailwindClasses(variantClasses);
  const sizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  const component = figma.createComponent();
  component.name = "variant=" + variant + ", size=" + size;
  component.description = variantDesc + ". " + sizeDesc;

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.paddingLeft = sizeStyles.paddingX || 12;
  component.paddingRight = sizeStyles.paddingX || 12;
  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.itemSpacing = sizeStyles.gap || 6;
  component.primaryAxisSizingMode = "AUTO"; // Hug contents
  component.counterAxisSizingMode = "FIXED";
  component.resize(100, sizeStyles.height || 36); // Width will auto-resize
  component.cornerRadius = sizeStyles.borderRadius || 8;

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background (ghost)
    component.fills = [];
  }

  // Apply stroke for variants with borders (ring or border)
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Create text label
  const fontWeight = 500; // font-medium
  const textNode = await createTextNode(
    "Button",
    sizeStyles.fontSize || 16,
    fontWeight,
  );
  textNode.name = "Label";

  // Apply text color from variant
  if (variantStyles.isWhiteText) {
    setWhiteTextColor(textNode);
  } else if (variantStyles.textVariable) {
    const textVar = getVariableByName(variantStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Generate Button ComponentSet with variant and size properties
 *
 * Creates a single "Button" ComponentSet with variants derived from
 * component-registry.json.
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections (for next section placement)
 */
export async function generateButtonTextComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  // Create Button section
  const section = getOrCreateSection(page, "Button");

  // Get variant and size keys from the registry
  const variants = variantProp.values;
  const sizes = sizeProp.values;

  // Generate all variant × size combinations
  const components: ComponentNode[] = [];

  // Layout as grid: variants as rows, sizes as columns
  var componentGap = 20;
  var rowHeight = 60; // Max height for a row

  for (var i = 0; i < variants.length; i++) {
    var currentX = 0;
    for (var j = 0; j < sizes.length; j++) {
      const component = await createButtonComponent(variants[i], sizes[j]);
      // Position in grid before combining
      component.x = currentX;
      component.y = i * rowHeight;
      currentX = currentX + component.width + componentGap;
      components.push(component);
    }
  }

  // Combine all into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Button";
  componentSet.description =
    "Button component with variant and size properties";

  // Move ComponentSet into section
  section.appendChild(componentSet);

  // Position ComponentSet with padding
  componentSet.x = SECTION_PADDING;
  componentSet.y = SECTION_PADDING;

  // Resize section to fit content with padding
  const totalWidth = componentSet.width + SECTION_PADDING * 2;
  const totalHeight = componentSet.height + SECTION_PADDING * 2;
  section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position section on page
  section.x = 100;
  section.y = startY;

  console.log(
    "✅ Generated Button ComponentSet with " +
      components.length +
      " variants (" +
      variants.length +
      " variants × " +
      sizes.length +
      " sizes)",
  );
  console.log(
    "Button section height: " + totalHeight + ", startY was: " + startY,
  );

  // Use totalHeight (calculated) instead of section.height (may not be updated yet)
  return startY + totalHeight + SECTION_GAP;
}

/**
 * Legacy exports for backwards compatibility with tests
 */
export var BUTTON_VARIANTS_EXPORT = variantProp.values;
export var BUTTON_SIZES_EXPORT = sizeProp.values;
export var BUTTON_STATES_EXPORT = ["Default"]; // Simplified - no state variants
