/**
 * Button Component Generator
 *
 * Generates a unified Button ComponentSet in Figma that matches
 * the Button component props exactly:
 *
 * - variant: primary, secondary, ghost, destructive, secondary-destructive, outline
 * - size: xs, sm, base, lg
 * - shape: base, square, circle
 * - disabled: true, false
 * - loading: true, false
 *
 * Reads all definitions from component-registry.json (the source of truth).
 *
 * @see packages/kumo/src/components/button/button.tsx
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  setWhiteTextColor,
  bindTextColorToVariable,
  BORDER_RADIUS,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
const buttonProps = registry.components.Button.props;

const variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

const sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

const shapeProp = buttonProps.shape as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Compact size mapping from button.tsx KUMO_BUTTON_VARIANTS.compactSize
 * Used for square and circle shapes
 */
const COMPACT_SIZE_MAP: Record<string, number> = {
  xs: 14, // size-3.5 = 14px
  sm: 26, // size-6.5 = 26px
  base: 36, // size-9 = 36px
  lg: 40, // size-10 = 40px
};

/**
 * Placeholder components for icons and loader
 */
type PlaceholderRefs = {
  placeholderIcon12?: ComponentNode;
  placeholderIcon16?: ComponentNode;
  placeholderIcon20?: ComponentNode;
  loader?: ComponentNode;
};

/**
 * Get placeholder icon component for a given size
 */
function getPlaceholderIconForSize(
  size: string,
  placeholders: PlaceholderRefs,
): ComponentNode | undefined {
  const iconSizeMap: Record<string, keyof PlaceholderRefs> = {
    xs: "placeholderIcon12",
    sm: "placeholderIcon16",
    base: "placeholderIcon20",
    lg: "placeholderIcon20",
  };
  const key = iconSizeMap[size];
  return key ? placeholders[key] : undefined;
}

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Create a single button component
 */
async function createButtonComponent(
  variant: string,
  size: string,
  shape: string,
  disabled: boolean,
  loading: boolean,
  placeholders: PlaceholderRefs,
): Promise<ComponentNode> {
  const variantClasses = variantProp.classes[variant] || "";
  const sizeClasses = sizeProp.classes[size] || "";

  // Parse styles from Tailwind classes
  const variantStyles = parseTailwindClasses(variantClasses);
  const sizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  const component = figma.createComponent();
  component.name = `variant=${variant}, size=${size}, shape=${shape}, disabled=${disabled}, loading=${loading}`;

  const isCompactShape = shape === "square" || shape === "circle";

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";

  if (isCompactShape) {
    // Square/circle: fixed size, no padding
    const buttonSize = COMPACT_SIZE_MAP[size] || 36;
    component.primaryAxisSizingMode = "FIXED";
    component.counterAxisSizingMode = "FIXED";
    component.resize(buttonSize, buttonSize);
    component.paddingLeft = 0;
    component.paddingRight = 0;
  } else {
    // Base shape: hug contents with padding
    component.primaryAxisSizingMode = "AUTO";
    component.counterAxisSizingMode = "FIXED";
    component.paddingLeft = sizeStyles.paddingX || 12;
    component.paddingRight = sizeStyles.paddingX || 12;
    component.resize(100, sizeStyles.height || 36);
  }

  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.itemSpacing = sizeStyles.gap || 6;

  // Set corner radius based on shape
  if (shape === "circle") {
    component.cornerRadius = BORDER_RADIUS.full;
  } else {
    // Both base and square use size-based radius
    component.cornerRadius =
      sizeStyles.borderRadius !== undefined
        ? sizeStyles.borderRadius
        : BORDER_RADIUS.lg;
  }

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background (ghost)
    component.fills = [];
  }

  // Apply stroke for variants with borders (ring or border)
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Apply disabled state: opacity-50
  if (disabled) {
    component.opacity = 0.5;
  }

  // Add loader for loading state
  if (loading && placeholders.loader) {
    const loaderInstance = placeholders.loader.createInstance();
    const loaderSize = size === "lg" ? 16 : 14;
    loaderInstance.resize(loaderSize, loaderSize);
    component.appendChild(loaderInstance);
  }

  // Add icon for compact shapes (when not loading)
  if (isCompactShape && !loading) {
    const placeholderIcon = getPlaceholderIconForSize(size, placeholders);
    if (placeholderIcon) {
      const iconInstance = placeholderIcon.createInstance();
      component.appendChild(iconInstance);
    }
  }

  // Add text label for base shape
  if (shape === "base") {
    const fontWeight = 500; // font-medium
    const labelText = loading ? "Loading..." : "Button";
    const textNode = await createTextNode(
      labelText,
      sizeStyles.fontSize || 16,
      fontWeight,
    );
    textNode.name = "Label";

    // Apply text color from variant
    if (variantStyles.isWhiteText) {
      setWhiteTextColor(textNode);
    } else if (variantStyles.textVariable) {
      const textVar = getVariableByName(variantStyles.textVariable);
      if (textVar) {
        bindTextColorToVariable(textNode, textVar.id);
      }
    }

    component.appendChild(textNode);
  }

  return component;
}

/**
 * Determine which combinations to generate.
 *
 * Instead of generating all 288 combinations (6×4×3×2×2), we generate
 * a reduced set that covers all use cases:
 *
 * 1. All variants × all sizes (shape=base, disabled=false, loading=false) = 24
 * 2. Disabled state: all variants, size=base only = 6
 * 3. Loading state: all variants, size=base only = 6
 * 4. Shape=square: all sizes, secondary variant only = 4
 * 5. Shape=circle: all sizes, secondary variant only = 4
 *
 * Total: ~44 components
 */
function shouldGenerateVariant(
  variant: string,
  size: string,
  shape: string,
  disabled: boolean,
  loading: boolean,
): boolean {
  // Base shape: generate all variants × sizes for default state
  if (shape === "base" && !disabled && !loading) {
    return true;
  }

  // Disabled: only show for base size, all variants
  if (shape === "base" && disabled && !loading && size === "base") {
    return true;
  }

  // Loading: only show for base size, all variants
  if (shape === "base" && loading && !disabled && size === "base") {
    return true;
  }

  // Square/circle shapes: only show secondary variant, all sizes
  if (
    (shape === "square" || shape === "circle") &&
    variant === "secondary" &&
    !disabled &&
    !loading
  ) {
    return true;
  }

  return false;
}

/**
 * Generate Button ComponentSet with reduced variants
 *
 * Creates a single "Button" ComponentSet with smart variant selection
 * that covers all use cases without redundancy. Then creates instances
 * in both light and dark mode sections.
 *
 * @param page - Target page for components
 * @param placeholders - Placeholder component references
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateButtonComponents(
  page: PageNode,
  placeholders: PlaceholderRefs = {},
  startY: number = 100,
): Promise<number> {
  figma.currentPage = page;

  const variants = variantProp.values;
  const sizes = sizeProp.values;
  const shapes = shapeProp.values;
  const disabledOptions = [false, true];
  const loadingOptions = [false, true];

  // Generate selected combinations only
  const components: ComponentNode[] = [];

  // Layout grid spacing
  const componentGap = 16;
  const rowGap = 80;

  // Track layout position by row type
  // - Rows 0-5: text buttons by variant (base shape)
  // - Row 6: square shape buttons
  // - Row 7: circle shape buttons
  const rowComponents: Map<number, ComponentNode[]> = new Map();

  for (const variant of variants) {
    for (const shape of shapes) {
      for (const disabled of disabledOptions) {
        for (const loading of loadingOptions) {
          for (const size of sizes) {
            if (
              !shouldGenerateVariant(variant, size, shape, disabled, loading)
            ) {
              continue;
            }

            const component = await createButtonComponent(
              variant,
              size,
              shape,
              disabled,
              loading,
              placeholders,
            );

            // Determine row based on shape
            let rowIndex: number;
            if (shape === "base") {
              // Text buttons grouped by variant
              rowIndex = variants.indexOf(variant);
            } else if (shape === "square") {
              // Square buttons in their own row after all variants
              rowIndex = variants.length;
            } else {
              // Circle buttons in their own row after square
              rowIndex = variants.length + 1;
            }

            if (!rowComponents.has(rowIndex)) {
              rowComponents.set(rowIndex, []);
            }
            rowComponents.get(rowIndex)!.push(component);
            components.push(component);
          }
        }
      }
    }
  }

  // Layout components in rows
  let yOffset = 0;
  const totalRows = variants.length + 2; // variants + square + circle
  for (let i = 0; i < totalRows; i++) {
    const row = rowComponents.get(i) || [];
    let xOffset = 0;

    for (const component of row) {
      component.x = xOffset;
      component.y = yOffset;
      xOffset += component.width + componentGap;
    }

    if (row.length > 0) {
      yOffset += rowGap;
    }
  }

  // Combine all into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Button";
  componentSet.description =
    "Button component with variant, size, shape, disabled, and loading properties";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions
  const contentWidth = componentSet.width;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "Button", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "Button", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING;
  componentSet.y = SECTION_PADDING;

  // Create instances of all components for dark section
  // Copy x/y positions directly from the original components
  for (const component of components) {
    const instance = component.createInstance();
    // Use same position as original component, offset by section padding
    instance.x = component.x + SECTION_PADDING;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Resize sections to fit content
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50; // Side by side with gap
  darkSection.section.y = startY;

  console.log(
    `✅ Generated Button ComponentSet with ${components.length} variants (light + dark)`,
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests and backwards compatibility
 */
export const BUTTON_VARIANTS_EXPORT = variantProp.values;
export const BUTTON_SIZES_EXPORT = sizeProp.values;
export const BUTTON_SHAPES_EXPORT = shapeProp.values;
export const BUTTON_DISABLED_OPTIONS = [false, true];
export const BUTTON_LOADING_OPTIONS = [false, true];
