/**
 * Button Component Generator
 *
 * Generates a unified Button ComponentSet in Figma that matches
 * the Button component props exactly:
 *
 * - variant: primary, secondary, ghost, destructive, secondary-destructive, outline
 * - size: xs, sm, base, lg
 * - shape: base, square, circle
 * - disabled: true, false
 * - loading: true, false
 *
 * Reads all definitions from component-registry.json (the source of truth).
 * Uses real icons from the Icon Library page.
 *
 * @see packages/kumo/src/components/button/button.tsx
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  createColumnHeaders,
  setWhiteTextColor,
  bindTextColorToVariable,
  BORDER_RADIUS,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";
import {
  getButtonIcon,
  createLoader,
  bindIconColor,
  DEFAULT_ICONS,
} from "./icon-utils";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
var buttonProps = registry.components.Button.props;

var variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

var sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

var shapeProp = buttonProps.shape as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Compact size mapping from button.tsx KUMO_BUTTON_VARIANTS.compactSize
 * Used for square and circle shapes
 */
var COMPACT_SIZE_MAP_LOCAL: Record<string, number> = {
  xs: 14, // size-3.5 = 14px
  sm: 26, // size-6.5 = 26px
  base: 36, // size-9 = 36px
  lg: 40, // size-10 = 40px
};

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 160;

/**
 * Create a single button component
 */
async function createButtonComponent(
  variant: string,
  size: string,
  shape: string,
  disabled: boolean,
  loading: boolean,
): Promise<ComponentNode> {
  var variantClasses = variantProp.classes[variant] || "";
  var sizeClasses = sizeProp.classes[size] || "";

  // Parse styles from Tailwind classes
  var variantStyles = parseTailwindClasses(variantClasses);
  var sizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  var component = figma.createComponent();
  component.name =
    "variant=" +
    variant +
    ", size=" +
    size +
    ", shape=" +
    shape +
    ", disabled=" +
    disabled +
    ", loading=" +
    loading;

  var isCompactShape = shape === "square" || shape === "circle";

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";

  if (isCompactShape) {
    // Square/circle: fixed size, no padding
    var buttonSize = COMPACT_SIZE_MAP_LOCAL[size] || 36;
    component.primaryAxisSizingMode = "FIXED";
    component.counterAxisSizingMode = "FIXED";
    component.resize(buttonSize, buttonSize);
    component.paddingLeft = 0;
    component.paddingRight = 0;
  } else {
    // Base shape: hug contents with padding
    component.primaryAxisSizingMode = "AUTO";
    component.counterAxisSizingMode = "FIXED";
    component.paddingLeft = sizeStyles.paddingX || 12;
    component.paddingRight = sizeStyles.paddingX || 12;
    component.resize(100, sizeStyles.height || 36);
  }

  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.itemSpacing = sizeStyles.gap || 6;

  // Set corner radius based on shape
  if (shape === "circle") {
    component.cornerRadius = BORDER_RADIUS.full;
  } else {
    // Both base and square use size-based radius
    component.cornerRadius =
      sizeStyles.borderRadius !== undefined
        ? sizeStyles.borderRadius
        : BORDER_RADIUS.lg;
  }

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    var fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background (ghost)
    component.fills = [];
  }

  // Apply stroke for variants with borders (ring or border)
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    var strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Apply disabled state: opacity-50
  if (disabled) {
    component.opacity = 0.5;
  }

  // Add loader for loading state
  if (loading) {
    var loaderSize = size === "lg" ? 16 : 14;
    var loader = createLoader(loaderSize);
    component.appendChild(loader);
  }

  // Add icon for compact shapes (when not loading)
  if (isCompactShape && !loading) {
    var icon = getButtonIcon(DEFAULT_ICONS.plus, size);

    // Bind icon color based on variant
    if (variantStyles.isWhiteText) {
      bindIconColor(icon, "text-white");
    } else if (variantStyles.textVariable) {
      bindIconColor(icon, variantStyles.textVariable);
    } else {
      bindIconColor(icon, "text-surface");
    }

    component.appendChild(icon);
  }

  // Add text label for base shape
  if (shape === "base") {
    var fontWeight = 500; // font-medium
    var labelText = loading ? "Loading..." : "Button";
    var textNode = await createTextNode(
      labelText,
      sizeStyles.fontSize || 16,
      fontWeight,
    );
    textNode.name = "Label";

    // Apply text color from variant
    if (variantStyles.isWhiteText) {
      setWhiteTextColor(textNode);
    } else if (variantStyles.textVariable) {
      var textVar = getVariableByName(variantStyles.textVariable);
      if (textVar) {
        bindTextColorToVariable(textNode, textVar.id);
      }
    }

    component.appendChild(textNode);
  }

  return component;
}

/**
 * Determine which combinations to generate.
 *
 * Instead of generating all 288 combinations (6×4×3×2×2), we generate
 * a reduced set that covers all use cases:
 *
 * 1. All variants × all sizes (shape=base, disabled=false, loading=false) = 24
 * 2. Disabled state: all variants, size=base only = 6
 * 3. Loading state: all variants, size=base only = 6
 * 4. Shape=square: all sizes, secondary variant only = 4
 * 5. Shape=circle: all sizes, secondary variant only = 4
 *
 * Total: ~44 components
 */
function shouldGenerateVariant(
  variant: string,
  size: string,
  shape: string,
  disabled: boolean,
  loading: boolean,
): boolean {
  // Base shape: generate all variants × sizes for default state
  if (shape === "base" && !disabled && !loading) {
    return true;
  }

  // Disabled: only show for base size, all variants
  if (shape === "base" && disabled && !loading && size === "base") {
    return true;
  }

  // Loading: only show for base size, all variants
  if (shape === "base" && loading && !disabled && size === "base") {
    return true;
  }

  // Square/circle shapes: only show secondary variant, all sizes
  if (
    (shape === "square" || shape === "circle") &&
    variant === "secondary" &&
    !disabled &&
    !loading
  ) {
    return true;
  }

  return false;
}

/**
 * Generate Button ComponentSet with reduced variants
 *
 * Creates a single "Button" ComponentSet with smart variant selection
 * that covers all use cases without redundancy. Then creates instances
 * in both light and dark mode sections.
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateButtonComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  var variants = variantProp.values;
  var sizes = sizeProp.values;
  var shapes = shapeProp.values;
  var disabledOptions = [false, true];
  var loadingOptions = [false, true];

  // Generate selected combinations only
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  // Layout grid spacing
  var componentGap = 16;
  var rowGap = 80;
  var headerRowHeight = 24; // Space for column headers at top
  var labelColumnWidth = 220; // Space for labels on the left

  // Track layout position by row type
  // - Rows 0-5: text buttons by variant (base shape)
  // - Row 6: square shape buttons
  // - Row 7: circle shape buttons
  var rowComponents: Map<number, ComponentNode[]> = new Map();

  // Track row labels by index
  var rowLabelTexts: Map<number, string> = new Map();

  // Track column headers: { x, text }
  var columnHeaders: { x: number; text: string }[] = [];

  for (var vi = 0; vi < variants.length; vi++) {
    var variant = variants[vi];
    for (var shi = 0; shi < shapes.length; shi++) {
      var shape = shapes[shi];
      for (var di = 0; di < disabledOptions.length; di++) {
        var disabled = disabledOptions[di];
        for (var li = 0; li < loadingOptions.length; li++) {
          var loading = loadingOptions[li];
          for (var si = 0; si < sizes.length; si++) {
            var size = sizes[si];
            if (
              !shouldGenerateVariant(variant, size, shape, disabled, loading)
            ) {
              continue;
            }

            var component = await createButtonComponent(
              variant,
              size,
              shape,
              disabled,
              loading,
            );

            // Determine row based on shape
            var rowIndex: number;
            if (shape === "base") {
              // Text buttons grouped by variant
              rowIndex = variants.indexOf(variant);
              rowLabelTexts.set(rowIndex, "variant=" + variant);
            } else if (shape === "square") {
              // Square buttons in their own row after all variants
              rowIndex = variants.length;
              rowLabelTexts.set(rowIndex, "shape=square");
            } else {
              // Circle buttons in their own row after square
              rowIndex = variants.length + 1;
              rowLabelTexts.set(rowIndex, "shape=circle");
            }

            if (!rowComponents.has(rowIndex)) {
              rowComponents.set(rowIndex, []);
            }
            rowComponents.get(rowIndex)!.push(component);
            components.push(component);
          }
        }
      }
    }
  }

  // Layout components in rows
  // First row (variant rows) will have column headers for sizes
  var yOffset = headerRowHeight; // Start below header row
  var totalRows = variants.length + 2; // variants + square + circle
  var columnHeadersRecorded = false;

  for (var i = 0; i < totalRows; i++) {
    var row = rowComponents.get(i) || [];
    var xOffset = labelColumnWidth;

    // Record row label position
    var labelText = rowLabelTexts.get(i);
    if (labelText && row.length > 0) {
      rowLabels.push({ y: yOffset, text: labelText });
    }

    for (var j = 0; j < row.length; j++) {
      var comp = row[j];
      comp.x = xOffset;
      comp.y = yOffset;

      // Record column headers from first variant row (sizes + disabled + loading)
      if (i === 0 && !columnHeadersRecorded) {
        // Parse component name to get size/state
        var nameParts = comp.name.split(", ");
        var sizeMatch = nameParts.find(function (p: string) {
          return p.startsWith("size=");
        });
        var disabledMatch = nameParts.find(function (p: string) {
          return p.startsWith("disabled=true");
        });
        var loadingMatch = nameParts.find(function (p: string) {
          return p.startsWith("loading=true");
        });

        var headerText = "";
        if (disabledMatch) {
          headerText = "disabled";
        } else if (loadingMatch) {
          headerText = "loading";
        } else if (sizeMatch) {
          headerText = sizeMatch; // "size=xs", "size=sm", etc.
        }

        if (headerText) {
          columnHeaders.push({ x: xOffset, text: headerText });
        }
      }

      xOffset += comp.width + componentGap;
    }

    if (i === 0 && row.length > 0) {
      columnHeadersRecorded = true;
    }

    if (row.length > 0) {
      yOffset += rowGap;
    }
  }

  // Combine all into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Button";
  componentSet.description =
    "Button component with variant, size, shape, disabled, and loading properties";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width and header row)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height + headerRowHeight;

  // Create light mode section
  var lightSection = createModeSection(page, "Button", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "Button", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING + headerRowHeight;

  // Add column headers to light section
  await createColumnHeaders(
    columnHeaders.map(function (h) {
      return { x: h.x + SECTION_PADDING, text: h.text };
    }),
    SECTION_PADDING,
    lightSection.frame,
  );

  // Add row labels to light section
  for (var li = 0; li < rowLabels.length; li++) {
    var label = rowLabels[li];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 12, // +12 to vertically center with button
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances of all components for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (var k = 0; k < components.length; k++) {
    var origComp = components[k];
    var instance = origComp.createInstance();
    instance.x = origComp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = origComp.y + SECTION_PADDING + headerRowHeight;
    darkSection.frame.appendChild(instance);
  }

  // Add column headers to dark section
  await createColumnHeaders(
    columnHeaders.map(function (h) {
      return { x: h.x + SECTION_PADDING, text: h.text };
    }),
    SECTION_PADDING,
    darkSection.frame,
  );

  // Add row labels to dark section
  for (var di = 0; di < rowLabels.length; di++) {
    var darkLabel = rowLabels[di];
    var darkLabelNode = await createRowLabel(
      darkLabel.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabel.y + 12,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  // Resize sections to fit content
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50; // Side by side with gap
  darkSection.section.y = startY;

  console.log(
    "✅ Generated Button ComponentSet with " +
      components.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests and backwards compatibility
 */
export var BUTTON_VARIANTS_EXPORT = variantProp.values;
export var BUTTON_SIZES_EXPORT = sizeProp.values;
export var BUTTON_SHAPES_EXPORT = shapeProp.values;
export var BUTTON_DISABLED_OPTIONS = [false, true];
export var BUTTON_LOADING_OPTIONS = [false, true];
