/**
 * Checkbox Component Generator
 *
 * Generates a high-quality Checkbox ComponentSet in Figma matching the code implementation.
 *
 * Component Structure (from checkbox.tsx):
 * - Outer container: horizontal layout with gap-2 (8px)
 * - Checkbox box: 16x16, rounded-sm (2px), with ring border
 * - Label text: text-base font-medium text-surface
 *
 * Properties:
 * - state: unchecked, checked, indeterminate
 * - variant: default, error
 * - disabled: true, false
 *
 * @see packages/kumo/src/components/checkbox/checkbox.tsx
 */

import {
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createTextNode,
  createRowLabel,
  bindTextColorToVariable,
  BORDER_RADIUS,
  FONT_SIZE,
} from "./shared";
import { createIconInstance, bindIconColor } from "./icon-utils";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
const checkboxProps = registry.components.Checkbox.props;

const variantProp = checkboxProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Checkbox box dimensions from checkbox.tsx (h-4 w-4 = 16px)
 */
const CHECKBOX_BOX_SIZE = 16;

/**
 * Icon sizes for check/minus icons (size="12" in source)
 */
const ICON_SIZE = 12;

/**
 * Gap between checkbox and label (gap-2 = 8px)
 */
const CHECKBOX_LABEL_GAP = 8;

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * State type for checkbox
 */
type CheckboxState = "unchecked" | "checked" | "indeterminate";

/**
 * Create the checkbox box (the 16x16 square with optional icon)
 */
function createCheckboxBox(
  state: CheckboxState,
  variant: string,
  _disabled: boolean,
): FrameNode {
  const box = figma.createFrame();
  box.name = "Checkbox Box";
  box.resize(CHECKBOX_BOX_SIZE, CHECKBOX_BOX_SIZE);

  // Auto-layout for centering icon
  box.layoutMode = "HORIZONTAL";
  box.primaryAxisAlignItems = "CENTER";
  box.counterAxisAlignItems = "CENTER";
  box.primaryAxisSizingMode = "FIXED";
  box.counterAxisSizingMode = "FIXED";

  // Border radius: rounded-sm = 2px
  box.cornerRadius = BORDER_RADIUS.sm;

  // Background fill
  // - Unchecked: bg-surface → color-surface
  // - Checked/Indeterminate: bg-surface-inverse → color-surface-inverse
  const isActive = state === "checked" || state === "indeterminate";
  const bgVariable = isActive ? "color-surface-inverse" : "color-surface";
  const bgVar = getVariableByName(bgVariable);
  if (bgVar) {
    bindFillToVariable(box, bgVar.id);
  }

  // Ring/border styling (Tailwind "ring" = 1px box-shadow, simulated with stroke)
  // - Default variant: ring-border → color-border
  // - Error variant: ring-error → color-error
  const ringVariable = variant === "error" ? "color-error" : "color-border";
  const ringVar = getVariableByName(ringVariable);
  if (ringVar) {
    bindStrokeToVariable(box, ringVar.id, 1);
  }

  // Add icon for checked or indeterminate state
  if (state === "indeterminate") {
    const minusIcon = createIconInstance("ph-minus", ICON_SIZE);
    if (minusIcon) {
      bindIconColor(minusIcon, "text-white");
      box.appendChild(minusIcon);
    }
  } else if (state === "checked") {
    const checkIcon = createIconInstance("ph-check", ICON_SIZE);
    if (checkIcon) {
      bindIconColor(checkIcon, "text-white");
      box.appendChild(checkIcon);
    }
  }

  return box;
}

/**
 * Create a single checkbox component with label
 */
async function createCheckboxComponent(
  state: CheckboxState,
  variant: string,
  disabled: boolean,
  labelText: string,
): Promise<ComponentNode> {
  const component = figma.createComponent();
  component.name = `state=${state}, variant=${variant}, disabled=${disabled}`;

  const variantDesc = variantProp.descriptions[variant] || "";
  component.description = variantDesc;

  // Configure as horizontal auto-layout (checkbox + label)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "CENTER";
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.itemSpacing = CHECKBOX_LABEL_GAP;
  component.fills = [];

  // Create checkbox box
  const checkboxBox = createCheckboxBox(state, variant, disabled);
  component.appendChild(checkboxBox);

  // Create label text
  // From checkbox.tsx: "text-base font-medium text-surface"
  const label = await createTextNode(labelText, FONT_SIZE.base, 500);

  // Bind text color to text-color-surface
  const textVar = getVariableByName("text-color-surface");
  if (textVar) {
    bindTextColorToVariable(label, textVar.id);
  }

  component.appendChild(label);

  // Apply disabled state: opacity-50
  if (disabled) {
    component.opacity = 0.5;
  }

  return component;
}

/**
 * Get a descriptive label for the checkbox state
 */
function getStateLabel(
  state: CheckboxState,
  variant: string,
  disabled: boolean,
): string {
  const parts: string[] = [];

  // State description
  if (state === "checked") {
    parts.push("Checked");
  } else if (state === "indeterminate") {
    parts.push("Indeterminate");
  } else {
    parts.push("Unchecked");
  }

  // Variant (only if error)
  if (variant === "error") {
    parts.push("Error");
  }

  // Disabled state
  if (disabled) {
    parts.push("Disabled");
  }

  return parts.join(" - ");
}

/**
 * Generate Checkbox ComponentSet
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateCheckboxComponents(
  page: PageNode,
  startY: number = 100,
): Promise<number> {
  figma.currentPage = page;

  const states: CheckboxState[] = ["unchecked", "checked", "indeterminate"];

  // Generate all meaningful combinations
  const components: ComponentNode[] = [];

  // Track row labels: { y, text }
  const rowLabels: { y: number; text: string }[] = [];

  // Layout grid spacing
  const componentGap = 24;
  const rowGap = 48; // Increased to make room for labels

  const labelColumnWidth = 180; // Space for labels on the left

  // Track layout - each scenario on its own row for readability
  let currentY = 0;

  // Row 1: Default variant - all states (unchecked, checked, indeterminate)
  rowLabels.push({ y: currentY, text: "variant=default" });
  let currentX = labelColumnWidth;
  for (const state of states) {
    const labelText = getStateLabel(state, "default", false);
    const component = await createCheckboxComponent(
      state,
      "default",
      false,
      labelText,
    );
    component.x = currentX;
    component.y = currentY;
    currentX += component.width + componentGap;
    components.push(component);
  }
  currentY += rowGap;

  // Row 2: Default variant - disabled states
  rowLabels.push({ y: currentY, text: "variant=default, disabled=true" });
  currentX = labelColumnWidth;
  for (const state of states) {
    const labelText = getStateLabel(state, "default", true);
    const component = await createCheckboxComponent(
      state,
      "default",
      true,
      labelText,
    );
    component.x = currentX;
    component.y = currentY;
    currentX += component.width + componentGap;
    components.push(component);
  }
  currentY += rowGap;

  // Row 3: Error variant - unchecked and checked only
  rowLabels.push({ y: currentY, text: "variant=error" });
  currentX = labelColumnWidth;
  for (const state of ["unchecked", "checked"] as CheckboxState[]) {
    const labelText = getStateLabel(state, "error", false);
    const component = await createCheckboxComponent(
      state,
      "error",
      false,
      labelText,
    );
    component.x = currentX;
    component.y = currentY;
    currentX += component.width + componentGap;
    components.push(component);
  }
  currentY += rowGap;

  // Row 4: Error variant - disabled (unchecked only)
  rowLabels.push({ y: currentY, text: "variant=error, disabled=true" });
  currentX = labelColumnWidth;
  {
    const labelText = getStateLabel("unchecked", "error", true);
    const component = await createCheckboxComponent(
      "unchecked",
      "error",
      true,
      labelText,
    );
    component.x = currentX;
    component.y = currentY;
    components.push(component);
  }

  // Combine into ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Checkbox";
  componentSet.description =
    "Checkbox component with state (unchecked/checked/indeterminate), variant (default/error), and disabled properties. Includes label text.";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width)
  const contentWidth = componentSet.width + labelColumnWidth;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "Checkbox", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "Checkbox", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 4, // +4 to vertically center with checkbox
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component.x/y are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 4,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    `✅ Generated Checkbox ComponentSet with ${components.length} variants (light + dark)`,
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export const CHECKBOX_VARIANTS_EXPORT = variantProp.values;
