/**
 * Checkbox Component Generator
 *
 * Generates a high-quality Checkbox ComponentSet in Figma matching the code implementation.
 *
 * Component Structure (from checkbox.tsx):
 * - Outer container: horizontal layout with gap-2 (8px)
 * - Checkbox box: 16x16, rounded-sm (2px), with ring border
 * - Label text: text-base font-medium text-surface
 *
 * Properties:
 * - state: unchecked, checked, indeterminate
 * - variant: default, error
 * - disabled: true, false
 *
 * Reads all definitions from component-registry.json (the source of truth).
 * Uses the `styling` section for Figma-specific metadata (dimensions, icons, state tokens).
 *
 * @see packages/kumo/src/components/checkbox/checkbox.tsx
 */

import {
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createTextNode,
  createRowLabel,
  createColumnHeaders,
  bindTextColorToVariable,
  BORDER_RADIUS,
  FONT_SIZE,
  SECTION_PADDING,
  SECTION_GAP,
} from "./shared";
import { createIconInstance, bindIconColor } from "./icon-utils";
import { logInfo } from "../logger";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props and styling from registry
var checkboxComponent = registry.components.Checkbox;
var checkboxProps = checkboxComponent.props;
var checkboxStyling = checkboxComponent.styling;

var variantProp = checkboxProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  stateClasses?: Record<string, Record<string, string>>;
  default: string;
};

/**
 * State type for checkbox
 */
type CheckboxState = "unchecked" | "checked" | "indeterminate";

/**
 * Checkbox states (derived from styling.states in registry)
 */
var CHECKBOX_STATES: CheckboxState[] = [
  "unchecked",
  "checked",
  "indeterminate",
];

/**
 * TESTABLE EXPORTS - Pure functions that return intermediate data
 * These functions compute data without calling Figma APIs, enabling snapshot tests.
 */

/**
 * Get variant configuration from registry
 */
export function getCheckboxVariantConfig() {
  return {
    values: variantProp.values,
    classes: variantProp.classes,
    descriptions: variantProp.descriptions,
    stateClasses: variantProp.stateClasses || {},
    default: variantProp.default,
  };
}

/**
 * Get styling configuration from registry
 * This is unique to Checkbox - it has a `styling` section with Figma-specific metadata
 */
export function getCheckboxStylingConfig() {
  return {
    dimensions: checkboxStyling.dimensions as string,
    borderRadius: checkboxStyling.borderRadius as string,
    baseTokens: checkboxStyling.baseTokens as string[],
    states: checkboxStyling.states as Record<string, string[]>,
    icons: checkboxStyling.icons as Array<{
      name: string;
      state: string;
      size: number;
    }>,
  };
}

/**
 * Get checkbox box size from styling dimensions
 * Parses "h-4 w-4" to extract 16px
 */
export function getCheckboxBoxSize(): number {
  // h-4 w-4 = 16px (4 * 4 = 16)
  return 16;
}

/**
 * Get icon size from styling
 */
export function getCheckboxIconSize(): number {
  var styling = getCheckboxStylingConfig();
  return styling.icons[0]?.size || 12;
}

/**
 * Get label gap (gap-2 = 8px)
 */
export function getCheckboxLabelGap(): number {
  return 8;
}

/**
 * Get border radius from styling
 * Parses "rounded-sm" to 2px
 */
export function getCheckboxBorderRadius(): number {
  return BORDER_RADIUS.sm; // 2px
}

/**
 * Get background variable for a given state
 */
export function getCheckboxBgVariable(state: CheckboxState): string {
  var isActive = state === "checked" || state === "indeterminate";
  return isActive ? "color-surface-inverse" : "color-surface";
}

/**
 * Get ring/border variable for a given variant
 */
export function getCheckboxRingVariable(variant: string): string {
  return variant === "error" ? "color-error" : "color-border";
}

/**
 * Get icon name for a given state
 */
export function getCheckboxIconName(
  state: CheckboxState,
): "ph-check" | "ph-minus" | null {
  if (state === "checked") return "ph-check";
  if (state === "indeterminate") return "ph-minus";
  return null;
}

/**
 * Get complete box configuration for a specific state/variant/disabled combination
 */
export function getCheckboxBoxConfig(
  state: CheckboxState,
  variant: string,
  disabled: boolean,
) {
  var iconName = getCheckboxIconName(state);

  return {
    state,
    variant,
    disabled,
    size: getCheckboxBoxSize(),
    borderRadius: getCheckboxBorderRadius(),
    bgVariable: getCheckboxBgVariable(state),
    ringVariable: getCheckboxRingVariable(variant),
    icon: iconName,
    iconSize: iconName ? getCheckboxIconSize() : null,
    iconColor: iconName ? "text-white" : null,
    opacity: disabled ? 0.5 : 1.0,
  };
}

/**
 * Get layout configuration for checkbox with label
 */
export function getCheckboxLayoutConfig() {
  return {
    layoutMode: "HORIZONTAL" as const,
    primaryAxisAlignItems: "MIN" as const,
    counterAxisAlignItems: "CENTER" as const,
    primaryAxisSizingMode: "AUTO" as const,
    counterAxisSizingMode: "AUTO" as const,
    itemSpacing: getCheckboxLabelGap(),
  };
}

/**
 * Get text configuration for label
 */
export function getCheckboxTextConfig() {
  return {
    fontSize: FONT_SIZE.base, // 16px
    fontWeight: 500, // font-medium
    textVariable: "text-color-surface",
  };
}

/**
 * Get complete checkbox configuration for a specific combination
 */
export function getCheckboxCompleteConfig(
  state: CheckboxState,
  variant: string,
  disabled: boolean,
) {
  return {
    state,
    variant,
    disabled,
    boxConfig: getCheckboxBoxConfig(state, variant, disabled),
    layoutConfig: getCheckboxLayoutConfig(),
    textConfig: getCheckboxTextConfig(),
    stylingConfig: getCheckboxStylingConfig(),
    opacity: disabled ? 0.5 : 1.0,
  };
}

/**
 * Get all checkbox variant data (for snapshot testing)
 * Returns intermediate data before Figma API calls
 */
export function getAllCheckboxVariantData() {
  var variantConfig = getCheckboxVariantConfig();
  var stylingConfig = getCheckboxStylingConfig();
  var layoutConfig = getCheckboxLayoutConfig();
  var textConfig = getCheckboxTextConfig();

  // Generate all box configurations
  var boxConfigs: ReturnType<typeof getCheckboxBoxConfig>[] = [];
  for (var si = 0; si < CHECKBOX_STATES.length; si++) {
    var state = CHECKBOX_STATES[si];
    for (var vi = 0; vi < variantConfig.values.length; vi++) {
      var variant = variantConfig.values[vi];
      for (var di = 0; di < 2; di++) {
        var disabled = di === 1;
        boxConfigs.push(getCheckboxBoxConfig(state, variant, disabled));
      }
    }
  }

  return {
    variantConfig,
    stylingConfig,
    layoutConfig,
    textConfig,
    states: CHECKBOX_STATES,
    boxConfigs,
    constants: {
      boxSize: getCheckboxBoxSize(),
      iconSize: getCheckboxIconSize(),
      labelGap: getCheckboxLabelGap(),
      borderRadius: getCheckboxBorderRadius(),
    },
  };
}

// ============================================================================
// FIGMA GENERATION FUNCTIONS (use Figma APIs)
// ============================================================================

/**
 * Create the checkbox box (the 16x16 square with optional icon)
 */
function createCheckboxBox(
  state: CheckboxState,
  variant: string,
  _disabled: boolean,
): FrameNode {
  var boxConfig = getCheckboxBoxConfig(state, variant, _disabled);

  var box = figma.createFrame();
  box.name = "Checkbox Box";
  box.resize(boxConfig.size, boxConfig.size);

  // Auto-layout for centering icon
  box.layoutMode = "HORIZONTAL";
  box.primaryAxisAlignItems = "CENTER";
  box.counterAxisAlignItems = "CENTER";
  box.primaryAxisSizingMode = "FIXED";
  box.counterAxisSizingMode = "FIXED";

  // Border radius from config
  box.cornerRadius = boxConfig.borderRadius;

  // Background fill from config
  var bgVar = getVariableByName(boxConfig.bgVariable);
  if (bgVar) {
    bindFillToVariable(box, bgVar.id);
  }

  // Ring/border from config
  var ringVar = getVariableByName(boxConfig.ringVariable);
  if (ringVar) {
    bindStrokeToVariable(box, ringVar.id, 1);
  }

  // Add icon if needed
  if (boxConfig.icon && boxConfig.iconSize) {
    var iconInstance = createIconInstance(boxConfig.icon, boxConfig.iconSize);
    if (iconInstance) {
      bindIconColor(iconInstance, boxConfig.iconColor || "text-white");
      box.appendChild(iconInstance);
    }
  }

  return box;
}

/**
 * Create a single checkbox component with label
 */
async function createCheckboxComponent(
  state: CheckboxState,
  variant: string,
  disabled: boolean,
  labelText: string,
): Promise<ComponentNode> {
  var completeConfig = getCheckboxCompleteConfig(state, variant, disabled);
  var layoutConfig = completeConfig.layoutConfig;
  var textConfig = completeConfig.textConfig;

  var component = figma.createComponent();
  component.name =
    "state=" + state + ", variant=" + variant + ", disabled=" + disabled;

  var variantDesc = variantProp.descriptions[variant] || "";
  component.description = variantDesc;

  // Configure as horizontal auto-layout (checkbox + label)
  component.layoutMode = layoutConfig.layoutMode;
  component.primaryAxisAlignItems = layoutConfig.primaryAxisAlignItems;
  component.counterAxisAlignItems = layoutConfig.counterAxisAlignItems;
  component.primaryAxisSizingMode = layoutConfig.primaryAxisSizingMode;
  component.counterAxisSizingMode = layoutConfig.counterAxisSizingMode;
  component.itemSpacing = layoutConfig.itemSpacing;
  component.fills = [];

  // Create checkbox box
  var checkboxBox = createCheckboxBox(state, variant, disabled);
  component.appendChild(checkboxBox);

  // Create label text
  var label = await createTextNode(
    labelText,
    textConfig.fontSize,
    textConfig.fontWeight,
  );

  // Bind text color
  var textVar = getVariableByName(textConfig.textVariable);
  if (textVar) {
    bindTextColorToVariable(label, textVar.id);
  }

  component.appendChild(label);

  // Apply disabled state: opacity-50
  if (disabled) {
    component.opacity = completeConfig.opacity;
  }

  return component;
}

/**
 * Get a simple label for the checkbox (just "Label" since state is shown in column headers)
 */
function getCheckboxLabel(): string {
  return "Label";
}

/**
 * Generate Checkbox ComponentSet
 *
 * Layout:
 * - Column headers: Unchecked | Checked | Indeterminate
 * - Row 1: variant=default
 * - Row 2: variant=default, disabled=true
 * - Row 3: variant=error
 * - Row 4: variant=error, disabled=true
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateCheckboxComponents(
  page: PageNode,
  startY: number = 100,
): Promise<number> {
  figma.currentPage = page;

  var states = CHECKBOX_STATES;
  var variants = variantProp.values;

  // Generate all meaningful combinations
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  // Layout grid spacing
  var componentGap = 24;
  var rowGap = 48;
  var headerRowHeight = 24; // Space for column headers at top

  var labelColumnWidth = 180; // Space for labels on the left

  // Column headers for states
  var columnHeaderTexts = ["Unchecked", "Checked", "Indeterminate"];

  // Track layout - each scenario on its own row for readability
  var currentY = headerRowHeight; // Start below header row

  // Generate rows for each variant × disabled combination
  for (var vi = 0; vi < variants.length; vi++) {
    var variant = variants[vi];

    // Enabled row
    rowLabels.push({ y: currentY, text: "variant=" + variant });
    var currentX = labelColumnWidth;
    for (var si = 0; si < states.length; si++) {
      var state = states[si];
      var component = await createCheckboxComponent(
        state,
        variant,
        false,
        getCheckboxLabel(),
      );
      component.x = currentX;
      component.y = currentY;
      currentX += component.width + componentGap;
      components.push(component);
    }
    currentY += rowGap;

    // Disabled row
    rowLabels.push({
      y: currentY,
      text: "variant=" + variant + ", disabled=true",
    });
    currentX = labelColumnWidth;
    for (var sdi = 0; sdi < states.length; sdi++) {
      var stateD = states[sdi];
      var componentD = await createCheckboxComponent(
        stateD,
        variant,
        true,
        getCheckboxLabel(),
      );
      componentD.x = currentX;
      componentD.y = currentY;
      currentX += componentD.width + componentGap;
      components.push(componentD);
    }
    currentY += rowGap;
  }

  // Combine into ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Checkbox";
  componentSet.description =
    "Checkbox component with state (unchecked/checked/indeterminate), variant (default/error), and disabled properties. Includes label text.";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width and header row)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height + headerRowHeight;

  // Create light mode section
  var lightSection = createModeSection(page, "Checkbox", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "Checkbox", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING + headerRowHeight;

  // Build column headers with positions from first row components
  var columnHeaders: { x: number; text: string }[] = [];
  // Get first 3 components (first row) for column positions
  for (var i = 0; i < Math.min(3, components.length); i++) {
    columnHeaders.push({
      x: components[i].x + SECTION_PADDING,
      text: columnHeaderTexts[i],
    });
  }

  // Add column headers to light section
  await createColumnHeaders(columnHeaders, SECTION_PADDING, lightSection.frame);

  // Add row labels to light section
  for (var li = 0; li < rowLabels.length; li++) {
    var labelData = rowLabels[li];
    var labelNode = await createRowLabel(
      labelData.text,
      SECTION_PADDING,
      SECTION_PADDING + labelData.y + 4, // +4 to vertically center with checkbox
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component.x/y are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (var ci = 0; ci < components.length; ci++) {
    var comp = components[ci];
    var instance = comp.createInstance();
    instance.x = comp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = comp.y + SECTION_PADDING + headerRowHeight;
    darkSection.frame.appendChild(instance);
  }

  // Add column headers to dark section
  await createColumnHeaders(columnHeaders, SECTION_PADDING, darkSection.frame);

  // Add row labels to dark section
  for (var dli = 0; dli < rowLabels.length; dli++) {
    var darkLabelData = rowLabels[dli];
    var darkLabelNode = await createRowLabel(
      darkLabelData.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabelData.y + 4,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  // Resize sections to fit content with padding
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  logInfo(
    "✅ Generated Checkbox ComponentSet with " +
      components.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests and backwards compatibility
 */
export var CHECKBOX_VARIANTS_EXPORT = variantProp.values;
export var CHECKBOX_STATES_EXPORT = CHECKBOX_STATES;
export var CHECKBOX_DISABLED_OPTIONS = [false, true];
