/**
 * ClipboardText Component Generator
 *
 * Generates a single ClipboardText ComponentSet in Figma with size property.
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * ## Component Structure
 * ClipboardText is a compound component with:
 * - Container with input-like styling (bg-secondary, ring-border, rounded)
 * - Text span with monospace font showing the copyable text
 * - Ghost button with clipboard icon on the right (separated by border)
 *
 * ## Size Variants
 * - sm: Extra small for compact UIs (text-xs, button size sm)
 * - base: Default size (text-sm, button size base)
 * - lg: Large for prominent display (text-sm, button size lg)
 */

import {
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
} from "./shared";
import { createIconInstance, bindIconColor } from "./icon-utils";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const clipboardTextProps = registry.components.ClipboardText.props;
const sizeProp = clipboardTextProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Input base styles (from inputVariants in input.tsx)
 * ClipboardText uses inputVariants for its container styling
 */
const INPUT_BASE_STYLES = "bg-secondary text-surface ring ring-border";

/**
 * ClipboardText base styles (from clipboardTextVariants)
 */
const CLIPBOARD_TEXT_BASE_STYLES = "bg-surface font-mono";

/**
 * Input size classes (from KUMO_INPUT_VARIANTS.size)
 * ClipboardText maps its sizes to input sizes via buttonSize
 */
const INPUT_SIZE_CLASSES: Record<string, string> = {
  xs: "h-5 gap-1 rounded-sm px-1.5 text-xs",
  sm: "h-6.5 gap-1 rounded-md px-2 text-xs",
  base: "h-9 gap-1.5 rounded-lg px-3 text-base",
  lg: "h-10 gap-2 rounded-lg px-4 text-base",
};

/**
 * Map ClipboardText size to button size (from KUMO_CLIPBOARD_TEXT_VARIANTS)
 */
const SIZE_TO_BUTTON_SIZE: Record<string, string> = {
  sm: "sm",
  base: "base",
  lg: "lg",
};

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Create a single ClipboardText component with the specified size
 */
async function createClipboardTextComponent(
  size: string,
): Promise<ComponentNode> {
  const sizeClasses = sizeProp.classes[size] || "";
  const description = sizeProp.descriptions[size] || "";

  // Get the button size for this clipboard text size
  const buttonSize = SIZE_TO_BUTTON_SIZE[size] || "base";
  const inputSizeClasses =
    INPUT_SIZE_CLASSES[buttonSize] || INPUT_SIZE_CLASSES.base;

  // Parse styles
  const inputBaseStyles = parseTailwindClasses(INPUT_BASE_STYLES);
  const inputSizeStyles = parseTailwindClasses(inputSizeClasses);
  const clipboardStyles = parseTailwindClasses(CLIPBOARD_TEXT_BASE_STYLES);
  const textSizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  const component = figma.createComponent();
  component.name = "size=" + size;
  component.description = description;

  // Set up auto-layout (horizontal: text + button)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.itemSpacing = 0; // No gap between text and button
  component.paddingLeft = 0;
  component.paddingRight = 0;
  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";

  // Apply corner radius from input size
  component.cornerRadius = inputSizeStyles.borderRadius || 8;

  // Apply fill - ClipboardText uses bg-surface (overrides input's bg-secondary)
  if (clipboardStyles.fillVariable) {
    const fillVar = getVariableByName(clipboardStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else if (inputBaseStyles.fillVariable) {
    const fillVar = getVariableByName(inputBaseStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  }

  // Apply border (ring-border from input)
  if (inputBaseStyles.strokeVariable) {
    const strokeVar = getVariableByName(inputBaseStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Create text container frame (holds the text with padding)
  const textFrame = figma.createFrame();
  textFrame.name = "TextContainer";
  textFrame.layoutMode = "HORIZONTAL";
  textFrame.primaryAxisAlignItems = "CENTER";
  textFrame.counterAxisAlignItems = "CENTER";
  textFrame.primaryAxisSizingMode = "AUTO";
  textFrame.counterAxisSizingMode = "FIXED";
  textFrame.fills = []; // Transparent
  textFrame.paddingLeft = inputSizeStyles.paddingX || 16;
  textFrame.paddingRight = inputSizeStyles.paddingX || 16;

  // Set height based on input size
  const heights: Record<string, number> = {
    xs: 20,
    sm: 26,
    base: 36,
    lg: 40,
  };
  textFrame.resize(100, heights[buttonSize] || 36);

  // Create text node with monospace font
  const fontSize = textSizeStyles.fontSize || inputSizeStyles.fontSize || 14;
  const textNode = figma.createText();

  // Load monospace font
  await figma.loadFontAsync({ family: "Roboto Mono", style: "Regular" });

  textNode.characters = "npm install @cloudflare/kumo";
  textNode.fontSize = fontSize;
  textNode.fontName = { family: "Roboto Mono", style: "Regular" };
  textNode.name = "Text";

  // Apply text color (text-surface from input)
  if (inputBaseStyles.textVariable) {
    const textVar = getVariableByName(inputBaseStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  textFrame.appendChild(textNode);
  component.appendChild(textFrame);

  // Create button frame (ghost button with icon)
  const buttonFrame = figma.createFrame();
  buttonFrame.name = "CopyButton";
  buttonFrame.layoutMode = "HORIZONTAL";
  buttonFrame.primaryAxisAlignItems = "CENTER";
  buttonFrame.counterAxisAlignItems = "CENTER";
  buttonFrame.primaryAxisSizingMode = "FIXED";
  buttonFrame.counterAxisSizingMode = "FIXED";
  buttonFrame.fills = []; // Transparent (ghost button)

  // Button padding
  const buttonPadding = 12;
  buttonFrame.paddingLeft = buttonPadding;
  buttonFrame.paddingRight = buttonPadding;

  // Set button size based on input height
  buttonFrame.resize(
    buttonPadding * 2 + 16, // padding + icon size
    heights[buttonSize] || 36,
  );

  // Add left border to button (border-l border-color)
  const borderColorVar = getVariableByName("color-color");
  if (borderColorVar) {
    buttonFrame.strokeLeftWeight = 1;
    buttonFrame.strokeTopWeight = 0;
    buttonFrame.strokeRightWeight = 0;
    buttonFrame.strokeBottomWeight = 0;
    buttonFrame.strokes = [
      {
        type: "SOLID",
        color: { r: 0.8, g: 0.8, b: 0.8 },
      },
    ];
    // Bind stroke to variable
    var stroke: SolidPaint = {
      type: "SOLID",
      color: { r: 0.8, g: 0.8, b: 0.8 },
    };
    stroke = figma.variables.setBoundVariableForPaint(
      stroke,
      "color",
      borderColorVar,
    );
    buttonFrame.strokes = [stroke];
  }

  // Create clipboard icon
  const iconSize = 16;
  const iconInstance = createIconInstance("ph-clipboard", iconSize);

  if (iconInstance) {
    iconInstance.name = "Icon";
    // Bind icon color to text-surface (inherits from parent in real component)
    bindIconColor(iconInstance, "text-color-surface");
    buttonFrame.appendChild(iconInstance);
  } else {
    // Fallback: create placeholder
    const iconPlaceholder = figma.createRectangle();
    iconPlaceholder.name = "Icon (placeholder)";
    iconPlaceholder.resize(iconSize, iconSize);
    iconPlaceholder.cornerRadius = 2;
    iconPlaceholder.fills = [
      { type: "SOLID", color: { r: 0.5, g: 0.5, b: 0.5 } },
    ];
    buttonFrame.appendChild(iconPlaceholder);
  }

  component.appendChild(buttonFrame);

  return component;
}

/**
 * Generate ClipboardText ComponentSet with size property
 *
 * Creates a single "ClipboardText" ComponentSet with sizes derived from
 * component-registry.json. Creates both light and dark mode sections.
 *
 * @param startY - Y position to start placing the section
 * @returns The Y position after this section (for next section placement)
 */
export async function generateClipboardTextComponents(
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  // Find or create Components page
  let componentsPage = figma.root.children.find(function (page) {
    return page.type === "PAGE" && page.name === "Components";
  }) as PageNode | undefined;

  if (!componentsPage) {
    componentsPage = figma.createPage();
    componentsPage.name = "Components";
  }

  figma.currentPage = componentsPage;

  // Get size keys from the registry
  const sizes = sizeProp.values;
  const components: ComponentNode[] = [];

  // Track row labels: { y, text }
  const rowLabels: { y: number; text: string }[] = [];

  // Layout spacing - vertical layout with labels
  const rowGap = 24;
  const labelColumnWidth = 140; // Space for labels on the left

  // Track position for laying out components vertically
  let currentY = 0;

  for (let i = 0; i < sizes.length; i++) {
    const size = sizes[i];
    const component = await createClipboardTextComponent(size);

    // Record row label
    rowLabels.push({ y: currentY, text: "size=" + size });

    // Position each component vertically with label offset
    component.x = labelColumnWidth;
    component.y = currentY;
    currentY += component.height + rowGap;
    components.push(component);
  }

  // Combine all variants into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, componentsPage);
  componentSet.name = "ClipboardText";
  componentSet.description =
    "ClipboardText component for displaying and copying text";

  // Calculate content dimensions (add label column width)
  const contentWidth = componentSet.width + labelColumnWidth;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(
    componentsPage,
    "ClipboardText",
    "light",
  );
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(
    componentsPage,
    "ClipboardText",
    "dark",
  );
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8, // +8 to vertically center
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated ClipboardText ComponentSet with " +
      sizes.length +
      " sizes (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}
