/**
 * CodeBlock Component Generator
 *
 * Generates a single CodeBlock ComponentSet in Figma with lang property variants.
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * CodeBlock is a Tier 2 component (wrapper around Code):
 * - Same lang variants as Code (ts, tsx, jsonc, bash, css)
 * - Adds container styling: border, background, padding
 * - Wraps monospace text inside a frame
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const codeBlockProps = registry.components.CodeBlock.props;
const langProp = codeBlockProps.lang as unknown as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * CodeBlock wrapper styles from code-block.tsx
 * Container: "min-w-0 rounded-md border border-color bg-surface [&>pre]:p-2.5!"
 * Inner Code: "m-0 w-auto rounded-none border-none bg-transparent p-0 font-mono text-sm leading-[20px] text-label"
 */
const CODE_BLOCK_WRAPPER_STYLES =
  "min-w-0 rounded-md border border-color bg-surface";
const CODE_INNER_PADDING = 10; // p-2.5 = 10px (from [&>pre]:p-2.5)

/**
 * Create a single CodeBlock component with the specified lang variant
 */
async function createCodeBlockComponent(lang: string): Promise<ComponentNode> {
  const _classes = langProp.classes[lang] || "";
  const description = langProp.descriptions[lang] || "";

  // Parse wrapper styles
  const wrapperStyles = parseTailwindClasses(CODE_BLOCK_WRAPPER_STYLES);

  // Create component with auto-layout
  const component = figma.createComponent();
  component.name = "lang=" + lang;
  component.description = description;

  // Set up auto-layout for frame container
  component.layoutMode = "VERTICAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "MIN";
  component.paddingLeft = CODE_INNER_PADDING;
  component.paddingRight = CODE_INNER_PADDING;
  component.paddingTop = CODE_INNER_PADDING;
  component.paddingBottom = CODE_INNER_PADDING;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.cornerRadius = wrapperStyles.borderRadius || 6; // rounded-md = 6px

  // Apply background (bg-surface)
  if (wrapperStyles.fillVariable) {
    const fillVar = getVariableByName(wrapperStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  }

  // Apply border (border-color)
  if (wrapperStyles.strokeVariable) {
    const strokeVar = getVariableByName(wrapperStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Create monospace text node
  const textNode = await createTextNode(
    'const hello = "world";',
    14, // text-sm = 14px
    400, // normal weight
  );
  textNode.name = "Code";

  // Load monospace font (JetBrains Mono as fallback, Inter as base)
  // Note: Figma plugin may not have JetBrains Mono, using Inter as approximation
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  textNode.fontName = { family: "Inter", style: "Regular" };

  // Apply text color (text-label)
  const labelVar = getVariableByName("text-color-label");
  if (labelVar) {
    bindTextColorToVariable(textNode, labelVar.id);
  }

  // Set line height (leading-[20px] = 20px)
  textNode.lineHeight = { value: 20, unit: "PIXELS" };

  component.appendChild(textNode);

  return component;
}

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Generate CodeBlock ComponentSet with lang property
 *
 * Creates a single "CodeBlock" ComponentSet with lang variants derived from
 * component-registry.json. Creates both light and dark mode sections.
 *
 * @param page - Page to create components on
 * @param startY - Y position to start placing the section
 * @returns The Y position after this section (for next section placement)
 */
export async function generateCodeBlockComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  // Use provided page (from main.ts)
  figma.currentPage = page;

  // Get lang keys from the registry
  const langs = langProp.values;
  const components: ComponentNode[] = [];

  // Track row labels: { y, text }
  const rowLabels: { y: number; text: string }[] = [];

  // Layout spacing - vertical layout with labels
  const rowGap = 40;
  const labelColumnWidth = 160; // Space for labels on the left

  // Track position for laying out components vertically
  let currentY = 0;

  for (let i = 0; i < langs.length; i++) {
    const lang = langs[i];
    const component = await createCodeBlockComponent(lang);

    // Record row label
    rowLabels.push({ y: currentY, text: "lang=" + lang });

    // Position each component vertically with label offset
    component.x = labelColumnWidth;
    component.y = currentY;
    currentY += component.height + rowGap;
    components.push(component);
  }

  // Combine all variants into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "CodeBlock";
  componentSet.description = "CodeBlock component with lang variants";

  // Calculate content dimensions (add label column width)
  const contentWidth = componentSet.width + labelColumnWidth;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "CodeBlock", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "CodeBlock", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8, // +8 to vertically center with code block
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated CodeBlock ComponentSet with " +
      langs.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}
