/**
 * Code Component Generator
 *
 * Generates a single Code ComponentSet in Figma with properties:
 * - lang: ts, tsx, jsonc, bash, css
 *
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * ## Implementation Notes
 *
 * The Code component is a simple typography primitive for displaying code snippets.
 * It has no backgrounds or borders (transparent), uses monospace font, and text-label color.
 *
 * ### Variant Categories
 * - lang variants: Only used for semantic meaning, no visual styling differences
 *
 * ### Base Styling (from code.tsx line 45)
 * "m-0 w-auto rounded-none border-none bg-transparent p-0 font-mono text-sm leading-[20px] text-label"
 */

import {
  createTextNode,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
} from "./shared";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

var codeProps = registry.components.Code.props;
var langProp = codeProps.lang as unknown as {
  values: string[];
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 160;

/**
 * Get placeholder text based on lang variant
 */
function getPlaceholderText(lang: string): string {
  if (lang === "bash") {
    return "npm install @cloudflare/kumo";
  }
  if (lang === "jsonc") {
    return '{ "key": "value" }';
  }
  if (lang === "css") {
    return ".class { color: blue; }";
  }
  if (lang === "tsx") {
    return "<Button>Click</Button>";
  }
  return 'const hello = "world";';
}

/**
 * Create a single Code component for a lang variant
 */
async function createCodeComponent(lang: string): Promise<ComponentNode> {
  var langDesc = langProp.descriptions[lang] || "";

  // Create component
  var component = figma.createComponent();

  // Name format: lang=X
  component.name = "lang=" + lang;
  component.description = langDesc;

  // Set up auto-layout (minimal - just wrapping text)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "MIN";
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";

  // No background or border for code components
  component.fills = [];

  // Create text node with monospace font
  var fontSize = 14; // text-sm = 14px
  var fontWeight = 400; // Regular weight for code
  var textNode = await createTextNode(
    getPlaceholderText(lang),
    fontSize,
    fontWeight,
  );
  textNode.name = "Text";

  // Load monospace font (Roboto Mono is reliably available in Figma)
  await figma.loadFontAsync({ family: "Roboto Mono", style: "Regular" });
  textNode.fontName = { family: "Roboto Mono", style: "Regular" };

  // Apply text color - text-label with fallback to text-surface
  var labelVar = getVariableByName("text-color-label");
  if (labelVar) {
    bindTextColorToVariable(textNode, labelVar.id);
  } else {
    // Fallback to text-surface if text-label doesn't exist
    var surfaceVar = getVariableByName("text-color-surface");
    if (surfaceVar) {
      bindTextColorToVariable(textNode, surfaceVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Generate Code ComponentSet with lang property
 *
 * Creates a single "Code" ComponentSet with variants derived from
 * component-registry.json. Creates both light and dark mode sections.
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections (for next section placement)
 */
export async function generateCodeComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  // Get lang keys from the registry
  var langs = langProp.values;

  // Generate components
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  // Layout configuration
  var rowHeight = 40;
  var labelColumnWidth = 160; // Space for labels on the left

  // Generate lang variants vertically
  for (var i = 0; i < langs.length; i++) {
    var lang = langs[i];

    // Record row label
    rowLabels.push({
      y: i * rowHeight,
      text: "lang=" + lang,
    });

    var component = await createCodeComponent(lang);
    component.x = labelColumnWidth;
    component.y = i * rowHeight;
    components.push(component);
  }

  // Combine all into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Code";
  componentSet.description =
    "Code component with lang property for displaying code snippets";

  // Disable auto-layout on the ComponentSet
  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height;

  // Create light mode section
  var lightSection = createModeSection(page, "Code", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "Code", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (var li = 0; li < rowLabels.length; li++) {
    var label = rowLabels[li];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8, // +8 to vertically center with text
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  for (var ci = 0; ci < components.length; ci++) {
    var comp = components[ci];
    var instance = comp.createInstance();
    instance.x = comp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = comp.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (var di = 0; di < rowLabels.length; di++) {
    var darkLabel = rowLabels[di];
    var darkLabelNode = await createRowLabel(
      darkLabel.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabel.y + 8,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  // Resize sections to fit content with padding
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated Code ComponentSet with " +
      components.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for testing - derived from registry
 */
export var CODE_LANGS_EXPORT = langProp.values;
