/**
 * CodeBlock Component Generator
 *
 * Generates a single CodeBlock ComponentSet in Figma with lang property variants.
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * CodeBlock is a Tier 2 component (wrapper around Code):
 * - Same lang variants as Code (ts, tsx, jsonc, bash, css)
 * - Adds container styling: border, background, padding
 * - Wraps monospace text inside a frame
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
  SECTION_PADDING,
  SECTION_GAP,
  FALLBACK_VALUES,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";
import { logComplete } from "../logger";

// Import variant data from the registry (generated by build:ai-metadata)
// CodeBlock uses the same lang variants as Code
import registry from "../../../../ai/component-registry.json";

var codeProps = registry.components.Code.props;
var langProp = codeProps.lang as unknown as {
  values: string[];
  descriptions: Record<string, string>;
  default: string;
};

/**
 * CodeBlock wrapper styles from code-block.tsx
 * Container: "min-w-0 rounded-md border border-color bg-surface [&>pre]:p-2.5!"
 */
var CODE_BLOCK_WRAPPER_STYLES =
  "min-w-0 rounded-md border border-color bg-surface";
var CODE_INNER_PADDING = 10; // p-2.5 = 10px



/**
 * TESTABLE EXPORTS - Pure functions that return intermediate data
 * These functions compute data without calling Figma APIs, enabling snapshot tests.
 */

/**
 * Get base styles for CodeBlock container
 * Returns container styling and inner padding info
 */
export function getBaseStyles() {
  const codeComponent = registry.components.Code as any;
  const codeStyling = codeComponent.styling;
  const containerStyles = (
    codeStyling.states.code_block_container as string[]
  ).join(" ");

  return {
    container: {
      raw: containerStyles,
      parsed: parseTailwindClasses(containerStyles),
    },
    innerPadding: CODE_INNER_PADDING, // p-2.5 = 10px
  };
}

/**
 * Get container configuration with dimensions and styling
 * Returns structured config for Figma container creation
 */
export function getContainerConfig() {
  const codeComponent = registry.components.Code as any;
  const codeStyling = codeComponent.styling;
  const containerStyles = (
    codeStyling.states.code_block_container as string[]
  ).join(" ");
  const parsed = parseTailwindClasses(containerStyles);

  return {
    borderRadius: parsed.borderRadius || FALLBACK_VALUES.borderRadius.medium,
    padding: CODE_INNER_PADDING,
    border: {
      hasBorder: parsed.hasBorder || false,
      strokeWeight: parsed.strokeWeight || FALLBACK_VALUES.strokeWeight,
      strokeVariable: parsed.strokeVariable || "",
    },
    fill: {
      fillVariable: parsed.fillVariable || "",
    },
  };
}

/**
 * Get complete intermediate data for all variants
 * Returns containerStyles + all lang variant data (for snapshot testing)
 */
export function getAllVariantData() {
  const codeComponent = registry.components.Code as any;
  const codeStyling = codeComponent.styling;
  const containerStyles = (
    codeStyling.states.code_block_container as string[]
  ).join(" ");
  const parsed = parseTailwindClasses(containerStyles);

  return {
    containerStyles: {
      raw: containerStyles,
      parsed,
    },
    variants: langProp.values.map((lang) => ({
      lang,
      description: langProp.descriptions[lang] || "",
      placeholderText: getPlaceholderText(lang),
    })),
  };
}

/**
 * Get placeholder text based on lang variant
 */
function getPlaceholderText(lang: string): string {
  if (lang === "bash") {
    return "npm install @cloudflare/kumo";
  }
  if (lang === "jsonc") {
    return '{ "key": "value" }';
  }
  if (lang === "css") {
    return ".class { color: blue; }";
  }
  if (lang === "tsx") {
    return "<Button>Click</Button>";
  }
  return 'const hello = "world";';
}

/**
 * Create a single CodeBlock component with the specified lang variant
 */
async function createCodeBlockComponent(lang: string): Promise<ComponentNode> {
  var description = langProp.descriptions[lang] || "";

  // Parse wrapper styles
  var wrapperStyles = parseTailwindClasses(CODE_BLOCK_WRAPPER_STYLES);

  // Create component with auto-layout
  var component = figma.createComponent();
  component.name = "lang=" + lang;
  component.description = description;

  // Set up auto-layout for frame container
  component.layoutMode = "VERTICAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "MIN";
  component.paddingLeft = CODE_INNER_PADDING;
  component.paddingRight = CODE_INNER_PADDING;
  component.paddingTop = CODE_INNER_PADDING;
  component.paddingBottom = CODE_INNER_PADDING;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.cornerRadius = wrapperStyles.borderRadius || FALLBACK_VALUES.borderRadius.medium;

  // Apply background (bg-surface)
  if (wrapperStyles.fillVariable) {
    var fillVar = getVariableByName(wrapperStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  }

  // Apply border (border-color)
  if (wrapperStyles.strokeVariable) {
    var strokeVar = getVariableByName(wrapperStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Create monospace text node
  var textNode = await createTextNode(getPlaceholderText(lang), 14, 400);
  textNode.name = "Code";

  // Load monospace font (Roboto Mono is reliably available in Figma)
  await figma.loadFontAsync({ family: "Roboto Mono", style: "Regular" });
  textNode.fontName = { family: "Roboto Mono", style: "Regular" };

  // Apply text color - text-label with fallback to text-surface
  var labelVar = getVariableByName("text-color-label");
  if (labelVar) {
    bindTextColorToVariable(textNode, labelVar.id);
  } else {
    // Fallback to text-surface if text-label doesn't exist
    var surfaceVar = getVariableByName("text-color-surface");
    if (surfaceVar) {
      bindTextColorToVariable(textNode, surfaceVar.id);
    }
  }

  // Set line height
  textNode.lineHeight = { value: 20, unit: "PIXELS" };

  component.appendChild(textNode);

  return component;
}

/**
 * Generate CodeBlock ComponentSet with lang property
 */
export async function generateCodeBlockComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  var langs = langProp.values;
  var components: ComponentNode[] = [];
  var rowLabels: { y: number; text: string }[] = [];

  var rowGap = 50;
  var labelColumnWidth = 160;
  var currentY = 0;

  for (var i = 0; i < langs.length; i++) {
    var lang = langs[i];
    var component = await createCodeBlockComponent(lang);

    rowLabels.push({ y: currentY, text: "lang=" + lang });

    component.x = labelColumnWidth;
    component.y = currentY;
    currentY = currentY + component.height + rowGap;
    components.push(component);
  }

  // @ts-ignore - combineAsVariants works at runtime
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "CodeBlock";
  componentSet.description = "CodeBlock component with lang variants";
  componentSet.layoutMode = "NONE";

  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height;

  var lightSection = createModeSection(page, "CodeBlock", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  var darkSection = createModeSection(page, "CodeBlock", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  for (var li = 0; li < rowLabels.length; li++) {
    var label = rowLabels[li];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8,
    );
    lightSection.frame.appendChild(labelNode);
  }

  for (var ci = 0; ci < components.length; ci++) {
    var comp = components[ci];
    var instance = comp.createInstance();
    instance.x = comp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = comp.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  for (var di = 0; di < rowLabels.length; di++) {
    var darkLabel = rowLabels[di];
    var darkLabelNode = await createRowLabel(
      darkLabel.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabel.y + 8,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  logComplete(
    "Generated CodeBlock ComponentSet with " +
      langs.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}
