/**
 * Code Component Generator
 *
 * Generates a single Code ComponentSet in Figma with properties:
 * - lang: ts, tsx, jsonc, bash, css
 *
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * ## Implementation Notes
 *
 * The Code component is a simple typography primitive for displaying code snippets.
 * It has no backgrounds or borders (transparent), uses monospace font, and text-label color.
 *
 * ### Variant Categories
 * - lang variants: Only used for semantic meaning, no visual styling differences
 *
 * ### Base Styling (from code.tsx line 45)
 * "m-0 w-auto rounded-none border-none bg-transparent p-0 font-mono text-sm leading-[20px] text-label"
 */

import {
  createTextNode,
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindTextColorToVariable,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

const codeProps = registry.components.Code.props;
const langProp = codeProps.lang as unknown as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Base code class applied to all Code components (from code.tsx line 45)
 */
const CODE_BASE_CLASS =
  "m-0 w-auto rounded-none border-none bg-transparent p-0 font-mono text-sm leading-[20px] text-label";

/**
 * Get placeholder text based on lang variant
 */
function getPlaceholderText(lang: string): string {
  if (lang === "bash") {
    return "npm install @cloudflare/kumo";
  }
  if (lang === "jsonc") {
    return '{ "key": "value" }';
  }
  if (lang === "css") {
    return ".class { color: blue; }";
  }
  if (lang === "tsx") {
    return "<Button>Click</Button>";
  }
  return 'const hello = "world";';
}

/**
 * Create a single Code component for a lang variant
 *
 * Follows the logic from code.tsx Code function (lines 77-88)
 */
async function createCodeComponent(lang: string): Promise<ComponentNode> {
  const langClasses = langProp.classes[lang] || "";
  const langDesc = langProp.descriptions[lang] || "";

  // Combine base + lang classes for parsing
  const combinedClasses = `${CODE_BASE_CLASS} ${langClasses}`.trim();

  // Parse all styles using the tailwind parser
  const styles = parseTailwindClasses(combinedClasses);

  // Create component
  const component = figma.createComponent();

  // Name format: lang=X
  component.name = "lang=" + lang;
  component.description = langDesc;

  // Set up auto-layout (minimal - just wrapping text)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "MIN";
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";

  // No background or border for code components
  component.fills = [];

  // Create text node with monospace font
  const fontSize = styles.fontSize || 14; // text-sm = 14px
  const fontWeight = 400; // Regular weight for code
  const textNode = await createTextNode(
    getPlaceholderText(lang),
    fontSize,
    fontWeight,
  );
  textNode.name = "Text";

  // Load monospace font
  await figma.loadFontAsync({ family: "SF Mono", style: "Regular" });
  textNode.fontName = { family: "SF Mono", style: "Regular" };

  // Apply text color - text-label
  const labelVar = getVariableByName("text-color-label");
  if (labelVar) {
    bindTextColorToVariable(textNode, labelVar.id);
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Generate Code ComponentSet with lang property
 *
 * Creates a single "Code" ComponentSet with variants derived from
 * component-registry.json. Creates both light and dark mode sections.
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections (for next section placement)
 */
export async function generateCodeComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  // Get lang keys from the registry
  const langs = langProp.values;

  // Generate components
  const components: ComponentNode[] = [];

  // Track row labels: { y, text }
  const rowLabels: { y: number; text: string }[] = [];

  // Layout configuration
  const rowHeight = 50;
  const labelColumnWidth = 160; // Space for labels on the left
  let currentRow = 0;

  // Generate lang variants in a single row
  for (let i = 0; i < langs.length; i++) {
    const lang = langs[i];

    // Record row label
    rowLabels.push({
      y: currentRow * rowHeight,
      text: "lang=" + lang,
    });

    const component = await createCodeComponent(lang);
    component.x = labelColumnWidth;
    component.y = currentRow * rowHeight;
    components.push(component);
    currentRow++;
  }

  // Combine all into a single ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Code";
  componentSet.description =
    "Code component with lang property for displaying code snippets";

  // Disable auto-layout on the ComponentSet
  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width)
  const contentWidth = componentSet.width + labelColumnWidth;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "Code", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "Code", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8, // +8 to vertically center with text
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (const label of rowLabels) {
    const labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 8,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated Code ComponentSet with " +
      components.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for testing - derived from registry
 */
export var CODE_LANGS_EXPORT = langProp.values;
