import { logComplete } from "../logger";
/**
 * LinkButton Component Generator
 *
 * Generates LinkButton ComponentSet in Figma with properties:
 * - variant: primary, secondary, ghost, destructive, secondary-destructive, outline
 * - size: xs, sm, base, lg
 * - hasIcon: true, false
 *
 * LinkButton is an anchor-styled button for navigation.
 * Default variant is "ghost" (unlike Button which defaults to "secondary").
 *
 * Uses real icons from the Icon Library page.
 *
 * @see packages/kumo/src/components/button/button.tsx
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  createColumnHeaders,
  setWhiteTextColor,
  bindTextColorToVariable,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";
import { getButtonIcon, bindIconColor, DEFAULT_ICONS } from "./icon-utils";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry (LinkButton uses same variants as Button)
var buttonProps = registry.components.Button.props;

var variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

var sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 160;

/**
 * Create a single link button component
 */
async function createLinkButtonComponent(
  variant: string,
  size: string,
  hasIcon: boolean,
): Promise<ComponentNode> {
  var variantClasses = variantProp.classes[variant] || "";
  var sizeClasses = sizeProp.classes[size] || "";
  var variantDesc = variantProp.descriptions[variant] || "";
  var sizeDesc = sizeProp.descriptions[size] || "";

  // Parse variant styles and size styles
  var variantStyles = parseTailwindClasses(variantClasses);
  var sizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  var component = figma.createComponent();
  component.name =
    "variant=" + variant + ", size=" + size + ", hasIcon=" + hasIcon;
  component.description = variantDesc + ". " + sizeDesc;

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.paddingLeft = sizeStyles.paddingX || 12;
  component.paddingRight = sizeStyles.paddingX || 12;
  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.itemSpacing = sizeStyles.gap || 6;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "FIXED";
  component.resize(100, sizeStyles.height || 36);

  // Set corner radius from size classes
  var cornerRadius =
    sizeStyles.borderRadius !== undefined ? sizeStyles.borderRadius : 8;
  component.cornerRadius = cornerRadius;

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    var fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background (ghost)
    component.fills = [];
  }

  // Apply stroke for variants with borders
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    var strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Add icon if hasIcon is true - use real icon from Icon Library
  if (hasIcon) {
    var icon = getButtonIcon(DEFAULT_ICONS.arrowRight, size);

    // Bind icon color to match text color
    if (variantStyles.isWhiteText) {
      bindIconColor(icon, "text-white");
    } else if (variantStyles.textVariable) {
      bindIconColor(icon, variantStyles.textVariable);
    } else {
      bindIconColor(icon, "text-surface");
    }

    component.appendChild(icon);
  }

  // Create text label
  var fontWeight = 500;
  var textNode = await createTextNode(
    "Link Button",
    sizeStyles.fontSize || 16,
    fontWeight,
  );
  textNode.name = "Label";

  // Apply text color from variant
  if (variantStyles.isWhiteText) {
    setWhiteTextColor(textNode);
  } else if (variantStyles.textVariable) {
    var textVar = getVariableByName(variantStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Generate LinkButton ComponentSet
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateLinkButtonComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  var variants = variantProp.values;
  var sizes = sizeProp.values;
  var hasIconOptions = [false, true];

  // Generate all combinations
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  // Track column headers: { x, text }
  var columnHeaders: { x: number; text: string }[] = [];
  var columnHeadersRecorded = false;

  var componentGap = 20;
  var iconGap = 40;
  var rowGap = 80; // Vertical space between variant rows
  var headerRowHeight = 24; // Space for column headers at top
  var labelColumnWidth = 220; // Space for labels on the left

  for (var v = 0; v < variants.length; v++) {
    // Record row label (offset by header row)
    rowLabels.push({
      y: v * rowGap + headerRowHeight,
      text: "variant=" + variants[v],
    });

    for (var hi = 0; hi < hasIconOptions.length; hi++) {
      var currentX = labelColumnWidth + hi * (sizes.length * 140 + iconGap);
      for (var sz = 0; sz < sizes.length; sz++) {
        var component = await createLinkButtonComponent(
          variants[v],
          sizes[sz],
          hasIconOptions[hi],
        );
        component.x = currentX;
        component.y = v * rowGap + headerRowHeight;

        // Record column headers from first row
        if (!columnHeadersRecorded) {
          var headerText =
            "size=" + sizes[sz] + (hasIconOptions[hi] ? " +icon" : "");
          columnHeaders.push({ x: currentX, text: headerText });
        }

        currentX = currentX + component.width + componentGap;
        components.push(component);
      }
    }
    if (!columnHeadersRecorded) {
      columnHeadersRecorded = true;
    }
  }

  // Combine into ComponentSet
  // @ts-ignore
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "LinkButton";
  componentSet.description =
    "LinkButton component for navigation with variant, size, and icon options";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width and header row)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height + headerRowHeight;

  // Create light mode section
  var lightSection = createModeSection(page, "LinkButton", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "LinkButton", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING + headerRowHeight;

  // Add column headers to light section
  await createColumnHeaders(
    columnHeaders.map(function (h) {
      return { x: h.x + SECTION_PADDING, text: h.text };
    }),
    SECTION_PADDING,
    lightSection.frame,
  );

  // Add row labels to light section
  for (var li = 0; li < rowLabels.length; li++) {
    var label = rowLabels[li];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 12,
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (var i = 0; i < components.length; i++) {
    var comp = components[i];
    var instance = comp.createInstance();
    instance.x = comp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = comp.y + SECTION_PADDING + headerRowHeight;
    darkSection.frame.appendChild(instance);
  }

  // Add column headers to dark section
  await createColumnHeaders(
    columnHeaders.map(function (h) {
      return { x: h.x + SECTION_PADDING, text: h.text };
    }),
    SECTION_PADDING,
    darkSection.frame,
  );

  // Add row labels to dark section
  for (var di = 0; di < rowLabels.length; di++) {
    var darkLabel = rowLabels[di];
    var darkLabelNode = await createRowLabel(
      darkLabel.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabel.y + 12,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  // Resize sections to fit content with padding
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  var totalComponents = variants.length * sizes.length * hasIconOptions.length;
  logComplete(
    "✅ Generated LinkButton ComponentSet with " +
      totalComponents +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export var LINK_BUTTON_VARIANTS_EXPORT = variantProp.values;
export var LINK_BUTTON_SIZES_EXPORT = sizeProp.values;
