/**
 * LinkButton Component Generator
 *
 * Generates LinkButton ComponentSet in Figma with properties:
 * - variant: primary, secondary, ghost, destructive, secondary-destructive, outline
 * - size: xs, sm, base, lg
 * - hasIcon: true, false
 *
 * LinkButton is an anchor-styled button for navigation.
 * Default variant is "ghost" (unlike Button which defaults to "secondary").
 *
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * @see button-text.ts - Button generator
 */

import {
  createTextNode,
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  setWhiteTextColor,
  bindTextColorToVariable,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry (LinkButton uses same variants as Button)
const buttonProps = registry.components.Button.props;

const variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

const sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Placeholder components for icon
 */
type PlaceholderRefs = {
  placeholderIcon12?: ComponentNode;
  placeholderIcon16?: ComponentNode;
  placeholderIcon20?: ComponentNode;
  loader?: ComponentNode;
};

/**
 * Get placeholder icon component for a given size
 */
function getPlaceholderIconForSize(
  size: string,
  placeholders: PlaceholderRefs,
): ComponentNode | undefined {
  const iconSizeMap: Record<string, keyof PlaceholderRefs> = {
    xs: "placeholderIcon12",
    sm: "placeholderIcon16",
    base: "placeholderIcon20",
    lg: "placeholderIcon20",
  };

  const key = iconSizeMap[size];
  return key ? placeholders[key] : undefined;
}

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Create a single link button component
 */
async function createLinkButtonComponent(
  variant: string,
  size: string,
  hasIcon: boolean,
  placeholders: PlaceholderRefs,
): Promise<ComponentNode> {
  const variantClasses = variantProp.classes[variant] || "";
  const sizeClasses = sizeProp.classes[size] || "";
  const variantDesc = variantProp.descriptions[variant] || "";
  const sizeDesc = sizeProp.descriptions[size] || "";

  // Parse variant styles and size styles
  const variantStyles = parseTailwindClasses(variantClasses);
  const sizeStyles = parseTailwindClasses(sizeClasses);

  // Create component
  const component = figma.createComponent();
  component.name = `variant=${variant}, size=${size}, hasIcon=${hasIcon}`;
  component.description = `${variantDesc}. ${sizeDesc}`;

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.paddingLeft = sizeStyles.paddingX || 12;
  component.paddingRight = sizeStyles.paddingX || 12;
  component.paddingTop = 0;
  component.paddingBottom = 0;
  component.itemSpacing = sizeStyles.gap || 6;
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "FIXED";
  component.resize(100, sizeStyles.height || 36);

  // Set corner radius from size classes
  const cornerRadius = sizeStyles.borderRadius ?? 8;
  component.cornerRadius = cornerRadius;

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  } else {
    // Transparent background (ghost)
    component.fills = [];
  }

  // Apply stroke for variants with borders
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Add icon if hasIcon is true
  if (hasIcon) {
    const placeholderIcon = getPlaceholderIconForSize(size, placeholders);
    if (placeholderIcon) {
      const iconInstance = placeholderIcon.createInstance();
      component.appendChild(iconInstance);
    }
  }

  // Create text label
  const fontWeight = 500;
  const textNode = await createTextNode(
    "Link Button",
    sizeStyles.fontSize || 16,
    fontWeight,
  );
  textNode.name = "Label";

  // Apply text color from variant
  if (variantStyles.isWhiteText) {
    setWhiteTextColor(textNode);
  } else if (variantStyles.textVariable) {
    const textVar = getVariableByName(variantStyles.textVariable);
    if (textVar) {
      bindTextColorToVariable(textNode, textVar.id);
    }
  }

  component.appendChild(textNode);

  return component;
}

/**
 * Generate LinkButton ComponentSet
 *
 * @param page - Target page for components
 * @param placeholders - Placeholder component references
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateLinkButtonComponents(
  page: PageNode,
  placeholders: PlaceholderRefs = {},
  startY: number = 100,
): Promise<number> {
  figma.currentPage = page;

  const variants = variantProp.values;
  const sizes = sizeProp.values;
  const hasIconOptions = [false, true];

  // Generate all combinations
  const components: ComponentNode[] = [];

  const componentGap = 20;
  const iconGap = 40;
  const rowGap = 80; // Vertical space between variant rows

  for (let v = 0; v < variants.length; v++) {
    for (let hi = 0; hi < hasIconOptions.length; hi++) {
      let currentX = hi * (sizes.length * 140 + iconGap);
      for (let sz = 0; sz < sizes.length; sz++) {
        const component = await createLinkButtonComponent(
          variants[v],
          sizes[sz],
          hasIconOptions[hi],
          placeholders,
        );
        component.x = currentX;
        component.y = v * rowGap;
        currentX = currentX + component.width + componentGap;
        components.push(component);
      }
    }
  }

  // Combine into ComponentSet
  // @ts-ignore
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "LinkButton";
  componentSet.description =
    "LinkButton component for navigation with variant, size, and icon options";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions
  const contentWidth = componentSet.width;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "LinkButton", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "LinkButton", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING;
  componentSet.y = SECTION_PADDING;

  // Create instances for dark section
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  const totalComponents =
    variants.length * sizes.length * hasIconOptions.length;
  console.log(
    `✅ Generated LinkButton ComponentSet with ${totalComponents} variants (light + dark)`,
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export const LINK_BUTTON_VARIANTS_EXPORT = variantProp.values;
export const LINK_BUTTON_SIZES_EXPORT = sizeProp.values;
