/**
 * Loader Component Generator
 *
 * Generates a Loader ComponentSet in Figma that matches
 * the Loader component structure from loader.tsx.
 *
 * Uses loader-data.json generated by build-loader-data.ts to stay
 * in sync with the actual component code.
 *
 * Sizes: sm (16px), base (24px), lg (32px)
 *
 * Note: Figma doesn't support SVG animations, so this shows a static
 * representation at the animation midpoint.
 *
 * @see packages/kumo/src/components/loader/loader.tsx
 * @see packages/kumo/scripts/figma/plugin/build-loader-data.ts
 */

import loaderData from "../generated/loader-data.json";
import {
  getVariableByName,
  createModeSection,
  createRowLabel,
  bindStrokeToVariable,
} from "./shared";

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 160;

/**
 * Create a single Loader component using figma.createNodeFromSvg()
 *
 * @param size - Size key (sm, base, lg)
 * @returns ComponentNode for the Loader
 */
async function createLoaderComponent(size: string): Promise<ComponentNode> {
  var sizeConfig = loaderData.sizes[size as keyof typeof loaderData.sizes];
  var sizeValue = sizeConfig.value;

  // Create component
  var component = figma.createComponent();
  component.name = "size=" + size;
  component.description = sizeConfig.description;

  // Set up frame
  component.resize(sizeValue, sizeValue);
  component.fills = [];
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";

  // Create SVG node from the loader SVG (parsed from loader.tsx)
  var svgString = loaderData.svgString;

  try {
    var svgNode = figma.createNodeFromSvg(svgString);
    svgNode.name = "Spinner";

    // Resize to match the component size
    svgNode.resize(sizeValue, sizeValue);

    // Set constraints to SCALE for proper resizing
    svgNode.constraints = {
      horizontal: "SCALE",
      vertical: "SCALE",
    };

    // Bind stroke colors to text-color-surface
    var strokeVar = getVariableByName("text-color-surface");
    if (strokeVar) {
      // Traverse all children and bind stroke colors
      traverseAndBindStrokes(svgNode, strokeVar.id);
    }

    component.appendChild(svgNode);
  } catch (error) {
    console.error("Failed to create SVG node for Loader:", error);
    // Fallback: create a simple ellipse
    var fallbackCircle = figma.createEllipse();
    fallbackCircle.name = "Fallback";
    fallbackCircle.resize(sizeValue - 4, sizeValue - 4);
    fallbackCircle.x = 2;
    fallbackCircle.y = 2;
    fallbackCircle.fills = [];
    fallbackCircle.strokes = [
      { type: "SOLID", color: { r: 0.5, g: 0.5, b: 0.5 } },
    ];
    fallbackCircle.strokeWeight = 2;
    component.appendChild(fallbackCircle);
  }

  return component;
}

/**
 * Traverse SVG node tree and bind stroke colors to a variable
 */
function traverseAndBindStrokes(node: SceneNode, variableId: string): void {
  // Check if this node type can have strokes
  if (
    node.type === "VECTOR" ||
    node.type === "ELLIPSE" ||
    node.type === "RECTANGLE" ||
    node.type === "LINE" ||
    node.type === "POLYGON" ||
    node.type === "STAR"
  ) {
    var strokeNode = node as
      | VectorNode
      | EllipseNode
      | RectangleNode
      | LineNode
      | PolygonNode
      | StarNode;
    if (strokeNode.strokes && strokeNode.strokes.length > 0) {
      var strokeWeight =
        typeof strokeNode.strokeWeight === "number"
          ? strokeNode.strokeWeight
          : 1;
      bindStrokeToVariable(node, variableId, strokeWeight);
    }
  }

  // Recursively process children for frames and groups
  if (node.type === "FRAME" || node.type === "GROUP") {
    var containerNode = node as FrameNode | GroupNode;
    for (var i = 0; i < containerNode.children.length; i++) {
      traverseAndBindStrokes(containerNode.children[i], variableId);
    }
  }
}

/**
 * Generate Loader ComponentSet
 *
 * Creates a "Loader" ComponentSet with size variants.
 * Creates both light and dark mode sections.
 *
 * @param page - The page to add components to
 * @param startY - Y position to start placing the section
 * @returns The Y position after this section (for next section placement)
 */
export async function generateLoaderComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  console.log("Loader: Starting generation at Y=" + startY);

  try {
    figma.currentPage = page;

    var sizes = Object.keys(loaderData.sizes);
    var components: ComponentNode[] = [];
    var rowLabels: { y: number; text: string }[] = [];

    var labelColumnWidth = 120;
    var componentGap = 24;
    var currentY = 0;

    // Create components for each size
    for (var i = 0; i < sizes.length; i++) {
      var size = sizes[i];
      var sizeValue =
        loaderData.sizes[size as keyof typeof loaderData.sizes].value;

      console.log("Loader: Creating size=" + size);
      var component = await createLoaderComponent(size);
      component.x = labelColumnWidth;
      component.y = currentY;

      rowLabels.push({ y: currentY, text: "size=" + size });
      components.push(component);

      currentY += sizeValue + componentGap;
    }

    console.log("Loader: Combining as variants...");
    // @ts-ignore - combineAsVariants works at runtime
    var componentSet = figma.combineAsVariants(components, page);
    componentSet.name = "Loader";
    componentSet.description =
      "Loader - Circular loading spinner. Sizes: sm (16px), base (24px), lg (32px). " +
      "Uses currentColor for stroke, so set text color on parent to change color. " +
      "Static representation of animated spinner from loader.tsx.";
    componentSet.layoutMode = "NONE";

    // Calculate content dimensions
    var contentWidth = componentSet.width + labelColumnWidth;
    var contentHeight = componentSet.height;

    // Create light mode section
    var lightSection = createModeSection(page, "Loader", "light");
    lightSection.frame.resize(
      contentWidth + SECTION_PADDING * 2,
      contentHeight + SECTION_PADDING * 2,
    );

    // Create dark mode section
    var darkSection = createModeSection(page, "Loader", "dark");
    darkSection.frame.resize(
      contentWidth + SECTION_PADDING * 2,
      contentHeight + SECTION_PADDING * 2,
    );

    // Move ComponentSet into light section frame
    lightSection.frame.appendChild(componentSet);
    componentSet.x = SECTION_PADDING + labelColumnWidth;
    componentSet.y = SECTION_PADDING;

    // Add row labels to light section
    for (var li = 0; li < rowLabels.length; li++) {
      var label = rowLabels[li];
      var labelNode = await createRowLabel(
        label.text,
        SECTION_PADDING,
        SECTION_PADDING + label.y + 4,
      );
      lightSection.frame.appendChild(labelNode);
    }

    // Create instances for dark section
    for (var k = 0; k < components.length; k++) {
      var origComp = components[k];
      var instance = origComp.createInstance();
      // Position relative to componentSet position, not origComp position
      instance.x = SECTION_PADDING + labelColumnWidth;
      instance.y = origComp.y + SECTION_PADDING;
      darkSection.frame.appendChild(instance);
    }

    // Add row labels to dark section
    for (var di = 0; di < rowLabels.length; di++) {
      var darkLabel = rowLabels[di];
      var darkLabelNode = await createRowLabel(
        darkLabel.text,
        SECTION_PADDING,
        SECTION_PADDING + darkLabel.y + 4,
      );
      darkSection.frame.appendChild(darkLabelNode);
    }

    // Resize sections to fit content with padding
    var totalWidth = contentWidth + SECTION_PADDING * 2;
    var totalHeight = contentHeight + SECTION_PADDING * 2;

    lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
    darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

    // Position sections side by side
    lightSection.section.x = 100;
    lightSection.section.y = startY;

    darkSection.section.x = 100 + totalWidth + 50;
    darkSection.section.y = startY;

    console.log(
      "Generated Loader ComponentSet with " +
        sizes.length +
        " variants (light + dark)",
    );

    return startY + totalHeight + SECTION_GAP;
  } catch (error) {
    var errorMessage = error instanceof Error ? error.message : String(error);
    var errorStack = error instanceof Error ? error.stack : "";
    console.error("Loader generation failed: " + errorMessage);
    console.error("Stack: " + errorStack);
    throw error;
  }
}
