import { logComplete } from "../logger";
/**
 * RefreshButton Component Generator
 *
 * Generates RefreshButton ComponentSet in Figma with properties:
 * - size: xs, sm, base, lg
 * - loading: true, false
 *
 * RefreshButton is a specialized square icon button with a refresh icon.
 * It uses shape="square" and variant="secondary" (default Button variant).
 *
 * Uses real icons from the Icon Library page.
 *
 * @see packages/kumo/src/components/button/button.tsx
 */

import {
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  createRowLabel,
  BORDER_RADIUS,
  SECTION_PADDING,
  SECTION_GAP,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";
import {
  getButtonIcon,
  createLoader,
  DEFAULT_ICONS,
  bindIconColor,
} from "./icon-utils";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
var buttonProps = registry.components.Button.props;

var variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

var sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Compact size mapping from button.tsx KUMO_BUTTON_VARIANTS.compactSize
 */
var COMPACT_SIZE_MAP: Record<string, number> = {
  xs: 14,
  sm: 26,
  base: 36,
  lg: 40,
};

/**
 * Refresh icon size by button size
 * From RefreshButton component: size-4.5 (base), size-4 (sm), size-5 (lg)
 */
var REFRESH_ICON_SIZE: Record<string, number> = {
  xs: 12,
  sm: 16, // size-4
  base: 18, // size-4.5
  lg: 20, // size-5
};

/**
 * Get border radius for size
 */
function getBorderRadiusForSize(size: string): number {
  var sizeClasses = sizeProp.classes[size] || "";
  var parsed = parseTailwindClasses(sizeClasses);
  return parsed.borderRadius !== undefined
    ? parsed.borderRadius
    : BORDER_RADIUS.lg;
}



/**
 * Create a single refresh button component
 */
function createRefreshButtonComponent(
  size: string,
  loading: boolean,
): ComponentNode {
  // RefreshButton uses secondary variant by default
  var variant = variantProp.default; // "secondary"
  var variantClasses = variantProp.classes[variant] || "";
  var variantStyles = parseTailwindClasses(variantClasses);

  var component = figma.createComponent();
  component.name = "size=" + size + ", loading=" + loading;
  component.description = "Refresh button for triggering data refresh";

  // Get dimensions from compact size (square button)
  var buttonSize = COMPACT_SIZE_MAP[size] || 36;

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.primaryAxisSizingMode = "FIXED";
  component.counterAxisSizingMode = "FIXED";
  component.resize(buttonSize, buttonSize);

  // Square shape uses size-based border radius
  component.cornerRadius = getBorderRadiusForSize(size);

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    var fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  }

  // Apply stroke for secondary variant
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    var strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Add refresh icon or loader
  var iconSize = REFRESH_ICON_SIZE[size] || 18;

  if (loading) {
    var loader = createLoader(iconSize);
    component.appendChild(loader);
  } else {
    // Use real refresh icon from Icon Library
    var icon = getButtonIcon(DEFAULT_ICONS.refresh, size);
    // Resize to match refresh button icon sizes
    if ("resize" in icon) {
      icon.resize(iconSize, iconSize);
    }

    // Bind icon color based on variant text color
    if (variantStyles.isWhiteText) {
      bindIconColor(icon, "text-white");
    } else if (variantStyles.textVariable) {
      bindIconColor(icon, variantStyles.textVariable);
    } else {
      bindIconColor(icon, "text-surface");
    }

    component.appendChild(icon);
  }

  return component;
}

/**
 * Generate RefreshButton ComponentSet
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateRefreshButtonComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  var sizes = sizeProp.values;
  var loadingOptions = [false, true];

  // Generate all combinations
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  var componentGap = 20;
  var rowGap = 60;
  var labelColumnWidth = 140; // Space for labels on the left

  // Layout vertically by loading state
  var currentY = 0;
  for (var lo = 0; lo < loadingOptions.length; lo++) {
    var loading = loadingOptions[lo];
    rowLabels.push({ y: currentY, text: "loading=" + loading });

    var currentX = labelColumnWidth;
    for (var sz = 0; sz < sizes.length; sz++) {
      var component = createRefreshButtonComponent(sizes[sz], loading);
      component.x = currentX;
      component.y = currentY;
      currentX = currentX + component.width + componentGap;
      components.push(component);
    }
    currentY += rowGap;
  }

  // Combine into ComponentSet
  // @ts-ignore
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "RefreshButton";
  componentSet.description =
    "RefreshButton component with size and loading state";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height;

  // Create light mode section
  var lightSection = createModeSection(page, "RefreshButton", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "RefreshButton", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING;

  // Add row labels to light section
  for (var li = 0; li < rowLabels.length; li++) {
    var label = rowLabels[li];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 10,
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component positions are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (var i = 0; i < components.length; i++) {
    var comp = components[i];
    var instance = comp.createInstance();
    instance.x = comp.x + SECTION_PADDING + labelColumnWidth;
    instance.y = comp.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Add row labels to dark section
  for (var di = 0; di < rowLabels.length; di++) {
    var darkLabel = rowLabels[di];
    var darkLabelNode = await createRowLabel(
      darkLabel.text,
      SECTION_PADDING,
      SECTION_PADDING + darkLabel.y + 10,
    );
    darkSection.frame.appendChild(darkLabelNode);
  }

  // Resize sections to fit content with padding
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  var totalComponents = sizes.length * loadingOptions.length;
  logComplete(
    "✅ Generated RefreshButton ComponentSet with " +
      totalComponents +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export var REFRESH_BUTTON_SIZES_EXPORT = sizeProp.values;
