/**
 * RefreshButton Component Generator
 *
 * Generates RefreshButton ComponentSet in Figma with properties:
 * - size: xs, sm, base, lg
 * - loading: true, false
 *
 * RefreshButton is a specialized square icon button with a refresh icon.
 * It uses shape="square" and variant="secondary" (default Button variant).
 *
 * Reads variant definitions from component-registry.json (the source of truth).
 *
 * @see button-icon.ts - Generic icon button generator
 */

import {
  bindFillToVariable,
  bindStrokeToVariable,
  getVariableByName,
  createModeSection,
  BORDER_RADIUS,
} from "./shared";
import { parseTailwindClasses } from "../parsers/tailwind-to-figma";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
const buttonProps = registry.components.Button.props;

const variantProp = buttonProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

const sizeProp = buttonProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Compact size mapping from button.tsx KUMO_BUTTON_VARIANTS.compactSize
 */
const COMPACT_SIZE_MAP: Record<string, number> = {
  xs: 14,
  sm: 26,
  base: 36,
  lg: 40,
};

/**
 * Refresh icon size by button size
 * From RefreshButton component: size-4.5 (base), size-4 (sm), size-5 (lg)
 */
const REFRESH_ICON_SIZE: Record<string, number> = {
  xs: 12,
  sm: 16, // size-4
  base: 18, // size-4.5
  lg: 20, // size-5
};

/**
 * Get border radius for size
 */
function getBorderRadiusForSize(size: string): number {
  const sizeClasses = sizeProp.classes[size] || "";
  const parsed = parseTailwindClasses(sizeClasses);
  return parsed.borderRadius !== undefined
    ? parsed.borderRadius
    : BORDER_RADIUS.lg;
}

/**
 * Placeholder components
 */
type PlaceholderRefs = {
  placeholderIcon12?: ComponentNode;
  placeholderIcon16?: ComponentNode;
  placeholderIcon20?: ComponentNode;
  loader?: ComponentNode;
  refreshIcon?: ComponentNode;
};

/**
 * Section padding for component display
 */
const SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
const SECTION_GAP = 160;

/**
 * Create a single refresh button component
 */
function createRefreshButtonComponent(
  size: string,
  loading: boolean,
  placeholders: PlaceholderRefs,
): ComponentNode {
  // RefreshButton uses secondary variant by default
  const variant = variantProp.default; // "secondary"
  const variantClasses = variantProp.classes[variant] || "";
  const variantStyles = parseTailwindClasses(variantClasses);

  const component = figma.createComponent();
  component.name = `size=${size}, loading=${loading}`;
  component.description = "Refresh button for triggering data refresh";

  // Get dimensions from compact size (square button)
  const buttonSize = COMPACT_SIZE_MAP[size] || 36;

  // Configure auto-layout
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "CENTER";
  component.counterAxisAlignItems = "CENTER";
  component.primaryAxisSizingMode = "FIXED";
  component.counterAxisSizingMode = "FIXED";
  component.resize(buttonSize, buttonSize);

  // Square shape uses size-based border radius
  component.cornerRadius = getBorderRadiusForSize(size);

  // Apply fill from variant
  if (variantStyles.fillVariable) {
    const fillVar = getVariableByName(variantStyles.fillVariable);
    if (fillVar) {
      bindFillToVariable(component, fillVar.id);
    }
  }

  // Apply stroke for secondary variant
  if (variantStyles.hasBorder && variantStyles.strokeVariable) {
    const strokeVar = getVariableByName(variantStyles.strokeVariable);
    if (strokeVar) {
      bindStrokeToVariable(component, strokeVar.id, 1);
    }
  }

  // Add refresh icon or loader
  const iconSize = REFRESH_ICON_SIZE[size] || 18;

  if (loading && placeholders.loader) {
    const loaderInstance = placeholders.loader.createInstance();
    loaderInstance.resize(iconSize, iconSize);
    component.appendChild(loaderInstance);
  } else if (placeholders.refreshIcon) {
    // Use dedicated refresh icon if available
    const iconInstance = placeholders.refreshIcon.createInstance();
    iconInstance.resize(iconSize, iconSize);
    component.appendChild(iconInstance);
  } else {
    // Fallback to placeholder icon
    const placeholderKey =
      iconSize <= 12
        ? "placeholderIcon12"
        : iconSize <= 16
          ? "placeholderIcon16"
          : "placeholderIcon20";
    const placeholder = placeholders[placeholderKey];
    if (placeholder) {
      const iconInstance = placeholder.createInstance();
      iconInstance.resize(iconSize, iconSize);
      component.appendChild(iconInstance);
    }
  }

  return component;
}

/**
 * Generate RefreshButton ComponentSet
 *
 * @param page - Target page for components
 * @param placeholders - Placeholder component references
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateRefreshButtonComponents(
  page: PageNode,
  placeholders: PlaceholderRefs = {},
  startY: number = 100,
): Promise<number> {
  figma.currentPage = page;

  const sizes = sizeProp.values;
  const loadingOptions = [false, true];

  // Generate all combinations
  const components: ComponentNode[] = [];

  const componentGap = 20;
  const loadingGap = 40;

  for (let lo = 0; lo < loadingOptions.length; lo++) {
    let currentX = lo * (sizes.length * 60 + loadingGap);
    for (let sz = 0; sz < sizes.length; sz++) {
      const component = createRefreshButtonComponent(
        sizes[sz],
        loadingOptions[lo],
        placeholders,
      );
      component.x = currentX;
      component.y = 0;
      currentX = currentX + component.width + componentGap;
      components.push(component);
    }
  }

  // Combine into ComponentSet
  // @ts-ignore
  const componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "RefreshButton";
  componentSet.description =
    "RefreshButton component with size and loading state";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions
  const contentWidth = componentSet.width;
  const contentHeight = componentSet.height;

  // Create light mode section
  const lightSection = createModeSection(page, "RefreshButton", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  const darkSection = createModeSection(page, "RefreshButton", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING;
  componentSet.y = SECTION_PADDING;

  // Create instances for dark section
  for (const component of components) {
    const instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING;
    instance.y = component.y + SECTION_PADDING;
    darkSection.frame.appendChild(instance);
  }

  // Resize sections to fit content with padding
  const totalWidth = contentWidth + SECTION_PADDING * 2;
  const totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  const totalComponents = sizes.length * loadingOptions.length;
  console.log(
    `✅ Generated RefreshButton ComponentSet with ${totalComponents} variants (light + dark)`,
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export const REFRESH_BUTTON_SIZES_EXPORT = sizeProp.values;
