/**
 * Switch Component Generator
 *
 * Generates a high-quality Switch ComponentSet in Figma matching the code implementation.
 *
 * Component Structure (from switch.tsx):
 * - Outer container: horizontal layout with gap-2 (8px)
 * - Switch track: rounded-full pill shape, bg-surface-3 when unchecked, bg-primary/bg-error when checked
 * - Switch thumb: circular, bg-white, translates right when checked
 * - Label text: text-base font-medium text-surface
 *
 * Properties:
 * - checked: false, true
 * - variant: default, error
 * - disabled: false, true
 * - size: sm, base, lg
 *
 * @see packages/kumo/src/components/switch/switch.tsx
 */

import {
  bindFillToVariable,
  getVariableByName,
  createModeSection,
  createTextNode,
  createRowLabel,
  createColumnHeaders,
  bindTextColorToVariable,
  BORDER_RADIUS,
  FONT_SIZE,
} from "./shared";

// Import variant data from the registry (generated by build:ai-metadata)
import registry from "../../../../ai/component-registry.json";

// Extract props from registry
var switchProps = registry.components.Switch.props;

var variantProp = switchProps.variant as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

var sizeProp = switchProps.size as {
  values: string[];
  classes: Record<string, string>;
  descriptions: Record<string, string>;
  default: string;
};

/**
 * Switch dimensions from switch.tsx
 * Size classes: h-5.5 w-8.5 (sm), h-6.5 w-10.5 (base), h-7.5 w-12.5 (lg)
 * Height includes the padding (p-1 = 4px = 2px * 2)
 * Thumb is "aspect-square h-full" (height of container minus padding)
 */
var SWITCH_DIMENSIONS: Record<string, { width: number; height: number }> = {
  sm: { width: 34, height: 22 }, // 8.5 * 4 = 34, 5.5 * 4 = 22
  base: { width: 42, height: 26 }, // 10.5 * 4 = 42, 6.5 * 4 = 26
  lg: { width: 50, height: 30 }, // 12.5 * 4 = 50, 7.5 * 4 = 30
};

/**
 * Thumb padding from switch.tsx (p-1 = 4px)
 */
var SWITCH_PADDING = 4;

/**
 * Gap between switch and label (gap-2 = 8px)
 */
var SWITCH_LABEL_GAP = 8;

/**
 * Section padding for component display
 */
var SECTION_PADDING = 48;

/**
 * Gap between sections on the page
 */
var SECTION_GAP = 160;

/**
 * Create the switch thumb (the circular moving part)
 */
function createSwitchThumb(size: string, checked: boolean): EllipseNode {
  var dimensions = SWITCH_DIMENSIONS[size];
  var thumbSize = dimensions.height - SWITCH_PADDING * 2;

  var thumb = figma.createEllipse();
  thumb.name = "Thumb";
  thumb.resize(thumbSize, thumbSize);

  // Background: white (not a variable, hardcoded in switch.tsx)
  thumb.fills = [
    {
      type: "SOLID",
      color: { r: 1, g: 1, b: 1 },
    },
  ];

  // Position: translate-x-full when checked
  if (checked) {
    thumb.x = dimensions.width - thumbSize - SWITCH_PADDING;
  } else {
    thumb.x = SWITCH_PADDING;
  }
  thumb.y = SWITCH_PADDING;

  return thumb;
}

/**
 * Create the switch track (the pill-shaped background)
 */
function createSwitchTrack(
  size: string,
  variant: string,
  checked: boolean,
  disabled: boolean,
): FrameNode {
  var dimensions = SWITCH_DIMENSIONS[size];

  var track = figma.createFrame();
  track.name = "Switch Track";
  track.resize(dimensions.width, dimensions.height);

  // No auto-layout for track - thumb positioned absolutely
  track.layoutMode = "NONE";

  // Border radius: rounded-full
  track.cornerRadius = BORDER_RADIUS.full;

  // Background fill based on state
  // - Unchecked: bg-surface-3
  // - Checked + default: bg-primary
  // - Checked + error: bg-error
  var bgVariableName = "color-surface-3";
  if (checked && !disabled) {
    if (variant === "error") {
      bgVariableName = "color-error";
    } else {
      bgVariableName = "color-primary";
    }
  }

  var bgVar = getVariableByName(bgVariableName);
  if (bgVar) {
    bindFillToVariable(track, bgVar.id);
  }

  // Border: border-transparent (no visible border in default state)
  // Note: The switch uses border-transparent, so we skip adding a stroke

  // Add the thumb
  var thumb = createSwitchThumb(size, checked);
  track.appendChild(thumb);

  return track;
}

/**
 * Create a single switch component with label
 */
async function createSwitchComponent(
  size: string,
  variant: string,
  checked: boolean,
  disabled: boolean,
  labelText: string,
): Promise<ComponentNode> {
  var component = figma.createComponent();
  component.name =
    "size=" +
    size +
    ", checked=" +
    checked +
    ", variant=" +
    variant +
    ", disabled=" +
    disabled;

  var variantDesc = variantProp.descriptions[variant] || "";
  var sizeDesc = sizeProp.descriptions[size] || "";
  component.description = variantDesc + " - " + sizeDesc;

  // Configure as horizontal auto-layout (switch + label)
  component.layoutMode = "HORIZONTAL";
  component.primaryAxisAlignItems = "MIN";
  component.counterAxisAlignItems = "CENTER";
  component.primaryAxisSizingMode = "AUTO";
  component.counterAxisSizingMode = "AUTO";
  component.itemSpacing = SWITCH_LABEL_GAP;
  component.fills = [];

  // Create switch track
  var switchTrack = createSwitchTrack(size, variant, checked, disabled);
  component.appendChild(switchTrack);

  // Create label text
  // From switch.tsx: "text-base font-medium text-surface"
  var label = await createTextNode(labelText, FONT_SIZE.base, 500);

  // Bind text color to text-color-surface
  var textVar = getVariableByName("text-color-surface");
  if (textVar) {
    bindTextColorToVariable(label, textVar.id);
  }

  component.appendChild(label);

  // Apply disabled state: opacity-50
  if (disabled) {
    component.opacity = 0.5;
  }

  return component;
}

/**
 * Get a simple label for the switch
 */
function getSwitchLabel(): string {
  return "Label";
}

/**
 * Generate Switch ComponentSet
 *
 * Layout:
 * - Column headers: size=sm | size=base | size=lg
 * - Row 1: checked=false, variant=default
 * - Row 2: checked=true, variant=default
 * - Row 3: checked=false, variant=default, disabled=true
 * - Row 4: checked=true, variant=default, disabled=true
 * - Row 5: checked=false, variant=error
 * - Row 6: checked=true, variant=error
 * - Row 7: checked=false, variant=error, disabled=true
 * - Row 8: checked=true, variant=error, disabled=true
 *
 * @param page - Target page for components
 * @param startY - Y position to start placing sections
 * @returns The Y position after all sections
 */
export async function generateSwitchComponents(
  page: PageNode,
  startY: number,
): Promise<number> {
  if (startY === undefined) startY = 100;

  figma.currentPage = page;

  var sizes: string[] = sizeProp.values;

  // Generate all meaningful combinations
  var components: ComponentNode[] = [];

  // Track row labels: { y, text }
  var rowLabels: { y: number; text: string }[] = [];

  // Layout grid spacing
  var componentGap = 24;
  var rowGap = 48;
  var headerRowHeight = 24; // Space for column headers at top

  var labelColumnWidth = 280; // Space for labels on the left

  // Column headers for sizes
  var columnHeaderTexts = ["size=sm", "size=base", "size=lg"];

  // Track layout - each scenario on its own row for readability
  var currentY = headerRowHeight; // Start below header row

  // Row 1: checked=false, variant=default
  rowLabels.push({ y: currentY, text: "checked=false, variant=default" });
  var currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "default",
      false,
      false,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 2: checked=true, variant=default
  rowLabels.push({ y: currentY, text: "checked=true, variant=default" });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "default",
      true,
      false,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 3: checked=false, variant=default, disabled=true
  rowLabels.push({
    y: currentY,
    text: "checked=false, variant=default, disabled=true",
  });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "default",
      false,
      true,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 4: checked=true, variant=default, disabled=true
  rowLabels.push({
    y: currentY,
    text: "checked=true, variant=default, disabled=true",
  });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "default",
      true,
      true,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 5: checked=false, variant=error
  rowLabels.push({ y: currentY, text: "checked=false, variant=error" });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "error",
      false,
      false,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 6: checked=true, variant=error
  rowLabels.push({ y: currentY, text: "checked=true, variant=error" });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "error",
      true,
      false,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 7: checked=false, variant=error, disabled=true
  rowLabels.push({
    y: currentY,
    text: "checked=false, variant=error, disabled=true",
  });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "error",
      false,
      true,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }
  currentY = currentY + rowGap;

  // Row 8: checked=true, variant=error, disabled=true
  rowLabels.push({
    y: currentY,
    text: "checked=true, variant=error, disabled=true",
  });
  currentX = labelColumnWidth;
  for (var i = 0; i < sizes.length; i++) {
    var component = await createSwitchComponent(
      sizes[i],
      "error",
      true,
      true,
      getSwitchLabel(),
    );
    component.x = currentX;
    component.y = currentY;
    currentX = currentX + component.width + componentGap;
    components.push(component);
  }

  // Combine into ComponentSet
  // @ts-ignore - combineAsVariants works at runtime
  var componentSet = figma.combineAsVariants(components, page);
  componentSet.name = "Switch";
  componentSet.description =
    "Switch component with size (sm/base/lg), checked (false/true), variant (default/error), and disabled properties. Includes label text.";

  componentSet.layoutMode = "NONE";

  // Calculate content dimensions (add label column width and header row)
  var contentWidth = componentSet.width + labelColumnWidth;
  var contentHeight = componentSet.height + headerRowHeight;

  // Create light mode section
  var lightSection = createModeSection(page, "Switch", "light");
  lightSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Create dark mode section
  var darkSection = createModeSection(page, "Switch", "dark");
  darkSection.frame.resize(
    contentWidth + SECTION_PADDING * 2,
    contentHeight + SECTION_PADDING * 2,
  );

  // Move ComponentSet into light section frame
  lightSection.frame.appendChild(componentSet);
  componentSet.x = SECTION_PADDING + labelColumnWidth;
  componentSet.y = SECTION_PADDING + headerRowHeight;

  // Build column headers with positions from first row components
  var columnHeaders: { x: number; text: string }[] = [];
  // Get first 3 components (first row) for column positions
  for (var i = 0; i < Math.min(3, components.length); i++) {
    columnHeaders.push({
      x: components[i].x + SECTION_PADDING,
      text: columnHeaderTexts[i],
    });
  }

  // Add column headers to light section
  await createColumnHeaders(columnHeaders, SECTION_PADDING, lightSection.frame);

  // Add row labels to light section
  for (var i = 0; i < rowLabels.length; i++) {
    var label = rowLabels[i];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 4, // +4 to vertically center with switch
    );
    lightSection.frame.appendChild(labelNode);
  }

  // Create instances for dark section
  // Note: component.x/y are relative to ComponentSet after combineAsVariants
  // We need to add labelColumnWidth to match the light section layout
  for (var i = 0; i < components.length; i++) {
    var component = components[i];
    var instance = component.createInstance();
    instance.x = component.x + SECTION_PADDING + labelColumnWidth;
    instance.y = component.y + SECTION_PADDING + headerRowHeight;
    darkSection.frame.appendChild(instance);
  }

  // Add column headers to dark section
  await createColumnHeaders(columnHeaders, SECTION_PADDING, darkSection.frame);

  // Add row labels to dark section
  for (var i = 0; i < rowLabels.length; i++) {
    var label = rowLabels[i];
    var labelNode = await createRowLabel(
      label.text,
      SECTION_PADDING,
      SECTION_PADDING + label.y + 4,
    );
    darkSection.frame.appendChild(labelNode);
  }

  // Resize sections to fit content with padding
  var totalWidth = contentWidth + SECTION_PADDING * 2;
  var totalHeight = contentHeight + SECTION_PADDING * 2;

  lightSection.section.resizeWithoutConstraints(totalWidth, totalHeight);
  darkSection.section.resizeWithoutConstraints(totalWidth, totalHeight);

  // Position sections side by side
  lightSection.section.x = 100;
  lightSection.section.y = startY;

  darkSection.section.x = 100 + totalWidth + 50;
  darkSection.section.y = startY;

  console.log(
    "✅ Generated Switch ComponentSet with " +
      components.length +
      " variants (light + dark)",
  );

  return startY + totalHeight + SECTION_GAP;
}

/**
 * Exports for tests
 */
export var SWITCH_VARIANTS_EXPORT = variantProp.values;
export var SWITCH_SIZES_EXPORT = sizeProp.values;
