import { type FC, useState, useEffect, useCallback } from "react";
import { CheckIcon, ClipboardIcon } from "@phosphor-icons/react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Button } from "../components/button";

// Import the markdown content as raw text (Vite handles ?raw imports)
import registryMarkdown from "../../ai/component-registry.md?raw";

export const ComponentRegistryView: FC = () => {
  const [content, setContent] = useState<string>(registryMarkdown || "");
  const [copied, setCopied] = useState(false);

  // Re-read on hot reload if needed
  useEffect(() => {
    setContent(registryMarkdown || "Loading component registry...");
  }, []);

  // Reset copied state after 2 seconds
  useEffect(() => {
    if (copied) {
      const timeout = setTimeout(() => setCopied(false), 2000);
      return () => clearTimeout(timeout);
    }
  }, [copied]);

  const copyToClipboard = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = content;
      textarea.style.position = "absolute";
      textarea.style.left = "-9999px";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
    }
  }, [content]);

  return (
    <div className="mx-auto max-w-4xl bg-surface p-8 text-surface">
      <div className="bg-info/10 mb-6 rounded-lg border border-info-border p-4">
        <div className="mb-2 flex items-center justify-between gap-4">
          <h2 className="text-lg font-semibold text-info">AI Agent Context</h2>
          <Button
            variant="outline"
            size="sm"
            onClick={copyToClipboard}
            aria-label={copied ? "Copied" : "Copy markdown to clipboard"}
          >
            {copied ? <CheckIcon size={14} /> : <ClipboardIcon size={14} />}
            {copied ? "Copied!" : "Copy"}
          </Button>
        </div>
        <p className="text-xs text-muted">
          This markdown is auto-generated by{" "}
          <code className="rounded bg-surface-secondary px-1 py-0.5">
            pnpm build:ai-metadata
          </code>{" "}
          and provides structured component metadata for AI agents and LLMs to
          understand and use Kumo components effectively.
        </p>
      </div>
      <article
        className={[
          "max-w-none text-sm leading-relaxed text-surface",
          // Headings
          "[&_h1]:mt-8 [&_h1]:mb-4 [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:text-surface",
          "[&_h2]:pb-2 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-surface",
          "[&_h3]:mt-5 [&_h3]:mb-2 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-surface",
          "[&_h4]:mt-4 [&_h4]:mb-2 [&_h4]:text-base [&_h4]:font-medium [&_h4]:text-surface",
          // Paragraphs and text
          "[&_p]:my-3 [&_strong]:font-semibold [&_strong]:text-surface",
          // Links
          "[&_a]:text-info [&_a]:underline",
          // Lists
          "[&_li]:my-1 [&_li]:marker:text-muted [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-6",
          // Blockquotes
          "[&_blockquote]:border-info [&_blockquote]:my-4 [&_blockquote]:border-l-4 [&_blockquote]:pl-4 [&_blockquote]:text-muted [&_blockquote]:italic",
          // Code
          "[&_code]:rounded [&_code]:bg-surface-secondary [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-xs",
          "[&_pre]:my-4 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:bg-surface-secondary [&_pre]:p-4 [&_pre_code]:bg-transparent [&_pre_code]:p-0",
          // Horizontal rules
          "[&_hr]:my-8 [&_hr]:border-color",
          // Tables
          "[&_table]:my-4 [&_table]:w-full [&_table]:border-collapse [&_table]:text-xs",
          "[&_th]:border [&_th]:border-color [&_th]:bg-surface-secondary [&_th]:px-3 [&_th]:py-2 [&_th]:text-left [&_th]:font-semibold",
          "[&_td]:border [&_td]:border-color [&_td]:px-3 [&_td]:py-2",
          "[&_tr:nth-child(even)]:bg-surface-secondary/50",
        ].join(" ")}
      >
        <Markdown remarkPlugins={[remarkGfm]}>{content}</Markdown>
      </article>
    </div>
  );
};
