import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("installation", "routes/installation.tsx"),
  route("accessibility", "routes/accessibility.tsx"),
  route("figma", "routes/figma.tsx"),
  route("playground", "routes/playground-sandpack.tsx"),
  route("api/generate", "routes/api.generate.tsx"),
  route("components/button", "routes/components.button.tsx"),
  route("components/input", "routes/components.input.tsx"),
  route("components/checkbox", "routes/components.checkbox.tsx"),
  route("components/select", "routes/components.select.tsx"),
  route("components/switch", "routes/components.switch.tsx"),
  route("components/field", "routes/components.field.tsx"),
  route("components/dialog", "routes/components.dialog.tsx"),
  route("components/tooltip", "routes/components.tooltip.tsx"),
  route("components/dropdown", "routes/components.dropdown.tsx"),
  route("components/expandable", "routes/components.expandable.tsx"),
  route("components/combobox", "routes/components.combobox.tsx"),
  route("components/loader", "routes/components.loader.tsx"),
  route("components/skeleton-line", "routes/components.skeleton-line.tsx"),
  route("components/clipboard-text", "routes/components.clipboard-text.tsx"),
  route("components/surface", "routes/components.surface.tsx"),
  route("components/code", "routes/components.code.tsx"),
  route("components/layer-card", "routes/components.layer-card.tsx"),
  route("components/menubar", "routes/components.menubar.tsx"),
  route("blocks/breadcrumbs", "routes/blocks.breadcrumbs.tsx"),
  route("blocks/empty", "routes/blocks.empty.tsx"),
  route("blocks/page-header", "routes/blocks.page-header.tsx"),
  route("layouts/resource-list", "routes/layouts.resource-list.tsx"),
] satisfies RouteConfig;
