/**
 * MR Reporter Utilities
 *
 * Handles building and posting consolidated MR comments from multiple reporters.
 */

import { Gitlab } from '@gitbeaker/rest';
import type { CIContext, ReportItem } from '../reporters/types';
import { GITLAB_HOST } from './gitlab-api';

/**
 * Build a consolidated markdown comment from report items
 */
export function buildMarkdownComment(items: ReportItem[], failures: string[] = []): string {
  // Sort by priority (lower = higher in comment)
  const sorted = [...items].sort((a, b) => a.priority - b.priority);

  const sections = sorted.map((item) => {
    return `### ${item.title}\n\n${item.content}`;
  });

  // Add warning section if there were failures
  if (failures.length > 0) {
    sections.push(`### ⚠️ Warning\n\nFailed to load ${failures.length} report artifact(s): ${failures.join(', ')}`);
  }

  const header = '## MR Release Summary\n';
  const footer =
    '\n---\n*Auto-generated by [Kumo CI](https://gitlab.cfdata.org/cloudflare/FE/kumo)*';

  return `${header}\n${sections.join('\n\n')}\n${footer}`;
}

/**
 * Post a new comment to the MR
 */
export async function postMRComment(
  context: CIContext,
  body: string,
): Promise<void> {
  const { projectId, mrIid, apiToken } = context;

  const missing: string[] = [];
  if (!projectId) missing.push('projectId (CI_PROJECT_ID)');
  if (!mrIid) missing.push('mrIid (CI_MERGE_REQUEST_IID)');
  if (!apiToken) missing.push('apiToken (GITLAB_API_TOKEN)');

  if (missing.length > 0) {
    console.log(`⚠️  Missing required variables: ${missing.join(', ')}`);
    return;
  }

  const api = new Gitlab({ host: GITLAB_HOST, token: apiToken });

  await api.MergeRequestNotes.create(projectId, Number(mrIid), body);

  console.log(`✅ Posted MR comment to !${mrIid}`);
}
