import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type KumoColor = {
  name: string;
  light: string;
  dark: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function main() {
  const cssPath = resolve(__dirname, "../../src/styles/kumo-binding.css");
  const outDir = resolve(__dirname, "./dist");
  const outFile = resolve(outDir, "storybook-colors.ts");

  const css = await readFile(cssPath, "utf8");

  const colorRegex =
    /(--(?:color|text-color)-kumo-[\w-]+):\s*light-dark\(\s*([\s\S]*?)\s*\);/g;

  const colors: KumoColor[] = [];

  for (const match of css.matchAll(colorRegex)) {
    const [, name, argsRaw] = match;

    let depth = 0;
    let splitIndex = -1;
    for (let i = 0; i < argsRaw.length; i++) {
      const ch = argsRaw[i];
      if (ch === "(") {
        depth++;
      } else if (ch === ")") {
        depth--;
      } else if (ch === "," && depth === 0) {
        splitIndex = i;
        break;
      }
    }

    if (splitIndex === -1) {
      continue;
    }

    const light = argsRaw.slice(0, splitIndex).trim();
    const dark = argsRaw.slice(splitIndex + 1).trim();

    colors.push({
      name,
      light,
      dark,
    });
  }

  await mkdir(outDir, { recursive: true });

  const fileContents =
    `// Auto-generated by scripts/color/build-colors-storybook.ts. Do not edit by hand.\n` +
    `\n` +
    `export type KumoColor = {\n` +
    `  name: string;\n` +
    `  light: string;\n` +
    `  dark: string;\n` +
    `};\n` +
    `\n` +
    `export const kumoColors: KumoColor[] = ${JSON.stringify(colors, null, 2)};\n`;

  await writeFile(outFile, fileContents, "utf8");

  // eslint-disable-next-line no-console
  console.log(`Generated ${colors.length} kumo colors to ${outFile}`);
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error("Failed to build Storybook colors:", error);
  process.exitCode = 1;
});
