import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Token type distinguishes between:
 * - "semantic": Base semantic tokens (e.g., --color-surface)
 * - "global": Theme-specific global tokens (e.g., --color-fedramp-surface)
 * - "override": Semantic overrides via data-theme (e.g., --color-surface in [data-theme="fedramp"])
 */
type TokenType = "semantic" | "global" | "override";

type KumoColor = {
  name: string;
  light: string;
  dark: string;
  theme: string;
  tokenType: TokenType;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function main() {
  const themeCssPath = resolve(__dirname, "../../src/styles/theme-kumo.css");
  const fedrampCssPath = resolve(
    __dirname,
    "../../src/styles/theme-fedramp.css",
  );
  const bindingCssPath = resolve(
    __dirname,
    "../../src/styles/kumo-binding.css",
  );
  const outDir = resolve(__dirname, "../../dist/color");
  const outFile = resolve(outDir, "storybook-colors.ts");

  const themeCss = await readFile(themeCssPath, "utf8");
  const fedrampCss = await readFile(fedrampCssPath, "utf8");
  const bindingCss = await readFile(bindingCssPath, "utf8");

  const colorRegex =
    /(--(?:color|text-color)-[\w-]+):\s*light-dark\(\s*([\s\S]*?)\s*\);/g;

  const colors: KumoColor[] = [];

  // Parse base semantic tokens from theme-kumo.css (default kumo theme)
  for (const match of themeCss.matchAll(colorRegex)) {
    const [, name, argsRaw] = match;
    const parsed = parseLightDarkArgs(argsRaw);
    if (parsed) {
      colors.push({
        name,
        light: parsed.light,
        dark: parsed.dark,
        theme: "kumo",
        tokenType: "semantic",
      });
    }
  }

  // Parse global fedramp tokens from theme-fedramp.css @theme block
  // These are explicit opt-in tokens like --color-fedramp-surface
  const themeBlockRegex = /@theme\s*\{([^}]+)\}/g;
  for (const blockMatch of fedrampCss.matchAll(themeBlockRegex)) {
    const [, blockContent] = blockMatch;
    for (const colorMatch of blockContent.matchAll(colorRegex)) {
      const [, name, argsRaw] = colorMatch;
      const parsed = parseLightDarkArgs(argsRaw);
      if (parsed) {
        colors.push({
          name,
          light: parsed.light,
          dark: parsed.dark,
          theme: "fedramp",
          tokenType: "global",
        });
      }
    }
  }

  // Parse semantic overrides from theme-fedramp.css @layer base block
  // These override base tokens when data-theme="fedramp" is set
  // Note: We strip CSS comments first to avoid matching commented-out tokens
  const layerBlockRegex = /@layer\s+base\s*\{([\s\S]*?)\n\}/g;
  for (const layerMatch of fedrampCss.matchAll(layerBlockRegex)) {
    const [, layerContent] = layerMatch;
    // Find [data-theme="..."] blocks within the layer
    const dataThemeRegex = /\[data-theme="([^"]+)"\]\s*\{([^}]+)\}/g;
    for (const themeMatch of layerContent.matchAll(dataThemeRegex)) {
      const [, themeName, blockContent] = themeMatch;
      // Strip CSS comments before parsing
      const withoutComments = blockContent.replace(/\/\*[\s\S]*?\*\//g, "");
      for (const colorMatch of withoutComments.matchAll(colorRegex)) {
        const [, name, argsRaw] = colorMatch;
        const parsed = parseLightDarkArgs(argsRaw);
        if (parsed) {
          colors.push({
            name,
            light: parsed.light,
            dark: parsed.dark,
            theme: themeName,
            tokenType: "override",
          });
        }
      }
    }
  }

  // Parse theme-specific overrides from kumo-binding.css (legacy location)
  const bindingThemeRegex = /\[data-theme="([^"]+)"\]\s*\{([^}]+)\}/g;
  for (const blockMatch of bindingCss.matchAll(bindingThemeRegex)) {
    const [, themeName, blockContent] = blockMatch;
    for (const colorMatch of blockContent.matchAll(colorRegex)) {
      const [, name, argsRaw] = colorMatch;
      const parsed = parseLightDarkArgs(argsRaw);
      if (parsed) {
        colors.push({
          name,
          light: parsed.light,
          dark: parsed.dark,
          theme: themeName,
          tokenType: "override",
        });
      }
    }
  }

  await mkdir(outDir, { recursive: true });

  const fileContents =
    `// Auto-generated by scripts/color/build-colors-storybook.ts. Do not edit by hand.\n` +
    `\n` +
    `/**\n` +
    ` * Token type distinguishes between:\n` +
    ` * - "semantic": Base semantic tokens (e.g., --color-surface)\n` +
    ` * - "global": Theme-specific global tokens (e.g., --color-fedramp-surface)\n` +
    ` * - "override": Semantic overrides via data-theme\n` +
    ` */\n` +
    `export type TokenType = "semantic" | "global" | "override";\n` +
    `\n` +
    `export type KumoColor = {\n` +
    `  name: string;\n` +
    `  light: string;\n` +
    `  dark: string;\n` +
    `  theme: string;\n` +
    `  tokenType: TokenType;\n` +
    `};\n` +
    `\n` +
    `export const kumoColors: KumoColor[] = ${JSON.stringify(colors, null, 2)};\n`;

  await writeFile(outFile, fileContents, "utf8");

  const semanticCount = colors.filter((c) => c.tokenType === "semantic").length;
  const globalCount = colors.filter((c) => c.tokenType === "global").length;
  const overrideCount = colors.filter((c) => c.tokenType === "override").length;
  // eslint-disable-next-line no-console
  console.log(
    `Generated ${semanticCount} semantic + ${globalCount} global + ${overrideCount} override tokens to ${outFile}`,
  );
}

function parseLightDarkArgs(
  argsRaw: string,
): { light: string; dark: string } | null {
  let depth = 0;
  let splitIndex = -1;
  for (let i = 0; i < argsRaw.length; i++) {
    const ch = argsRaw[i];
    if (ch === "(") {
      depth++;
    } else if (ch === ")") {
      depth--;
    } else if (ch === "," && depth === 0) {
      splitIndex = i;
      break;
    }
  }

  if (splitIndex === -1) {
    return null;
  }

  const light = argsRaw.slice(0, splitIndex).trim();
  const dark = argsRaw.slice(splitIndex + 1).trim();
  return { light, dark };
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error("Failed to build Storybook colors:", error);
  process.exitCode = 1;
});
