import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type KumoColor = {
  name: string;
  light: string;
  dark: string;
  theme?: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function main() {
  const themeCssPath = resolve(__dirname, "../../src/styles/theme-kumo.css");
  const bindingCssPath = resolve(
    __dirname,
    "../../src/styles/kumo-binding.css",
  );
  const outDir = resolve(__dirname, "../../dist/color");
  const outFile = resolve(outDir, "storybook-colors.ts");

  const themeCss = await readFile(themeCssPath, "utf8");
  const bindingCss = await readFile(bindingCssPath, "utf8");

  const colorRegex =
    /(--(?:color|text-color)-[\w-]+):\s*light-dark\(\s*([\s\S]*?)\s*\);/g;

  const colors: KumoColor[] = [];

  // Parse base theme colors from theme-kumo.css (default kumo theme)
  for (const match of themeCss.matchAll(colorRegex)) {
    const [, name, argsRaw] = match;
    const parsed = parseLightDarkArgs(argsRaw);
    if (parsed) {
      colors.push({
        name,
        light: parsed.light,
        dark: parsed.dark,
        theme: "kumo",
      });
    }
  }

  // Parse theme-specific overrides from kumo-binding.css
  const themeBlockRegex = /\[data-theme="([^"]+)"\]\s*\{([^}]+)\}/g;
  for (const blockMatch of bindingCss.matchAll(themeBlockRegex)) {
    const [, themeName, blockContent] = blockMatch;
    for (const colorMatch of blockContent.matchAll(colorRegex)) {
      const [, name, argsRaw] = colorMatch;
      const parsed = parseLightDarkArgs(argsRaw);
      if (parsed) {
        colors.push({
          name,
          light: parsed.light,
          dark: parsed.dark,
          theme: themeName,
        });
      }
    }
  }

  await mkdir(outDir, { recursive: true });

  const fileContents =
    `// Auto-generated by scripts/color/build-colors-storybook.ts. Do not edit by hand.\n` +
    `\n` +
    `export type KumoColor = {\n` +
    `  name: string;\n` +
    `  light: string;\n` +
    `  dark: string;\n` +
    `  theme: string;\n` +
    `};\n` +
    `\n` +
    `export const kumoColors: KumoColor[] = ${JSON.stringify(colors, null, 2)};\n`;

  await writeFile(outFile, fileContents, "utf8");

  const kumoCount = colors.filter((c) => c.theme === "kumo").length;
  const otherThemes = [
    ...new Set(colors.filter((c) => c.theme !== "kumo").map((c) => c.theme)),
  ];
  const overrideCount = colors.filter((c) => c.theme !== "kumo").length;
  // eslint-disable-next-line no-console
  console.log(
    `Generated ${kumoCount} kumo colors + ${overrideCount} overrides (${otherThemes.join(", ")}) to ${outFile}`,
  );
}

function parseLightDarkArgs(
  argsRaw: string,
): { light: string; dark: string } | null {
  let depth = 0;
  let splitIndex = -1;
  for (let i = 0; i < argsRaw.length; i++) {
    const ch = argsRaw[i];
    if (ch === "(") {
      depth++;
    } else if (ch === ")") {
      depth--;
    } else if (ch === "," && depth === 0) {
      splitIndex = i;
      break;
    }
  }

  if (splitIndex === -1) {
    return null;
  }

  const light = argsRaw.slice(0, splitIndex).trim();
  const dark = argsRaw.slice(splitIndex + 1).trim();
  return { light, dark };
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error("Failed to build Storybook colors:", error);
  process.exitCode = 1;
});
